import {useCampaignLanguage, campaignWeekdays} from '../../context/campaignLanguage';
import {useEffect,useState,useCallback} from 'react';
import {useParams,useLocation,useNavigate,Link} from 'react-router-dom';
import {api} from '../../api';
import CampaignDetail from '../../pages/CampaignDetail';
import {Panel,Metric,Button,Badge,Icon,Empty,ErrorNotice,dateTime} from '../ui';
import ActivityChart from '../ActivityChart';
import CampaignSetupSteps, {campaignSetupSteps} from '../CampaignSetupSteps';
import CampaignPreflight from '../CampaignPreflight';
import CampaignSettings from '../CampaignSettings';
import CampaignActivity from '../CampaignActivity';
const tabs=[['overview','Przegląd'],['sequences','Sekwencja'],['leads','Odbiorcy'],['inboxes','Skrzynki'],['settings','Ustawienia'],['analytics','Analityka'],['queue','Aktywność']];
const plain=html=>new DOMParser().parseFromString(html||'','text/html').body.textContent||'';
export default function CampaignWorkspace(){
 const {ct,language}=useCampaignLanguage();
 const {id}=useParams(),location=useLocation(),tab=location.hash.slice(1)||'overview';
 const navigate=useNavigate();
 const setup=new URLSearchParams(location.search).get('setup')==='1';
 const stepIndex=Math.max(0,campaignSetupSteps.findIndex(([key])=>key===tab));
 const [inboxSelection,setInboxSelection]=useState([]);
 const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[report,setReport]=useState(null),[calendar,setCalendar]=useState(null),[details,setDetails]=useState(false),[saved,setSaved]=useState('');
 const load=useCallback(async()=>{
  try{const from=new Date();from.setUTCDate(from.getUTCDate()-6);
   const [campaign,inboxes,sequences,leads,daily]=await Promise.all([api.get('/campaigns/'+id),api.get('/inboxes'),api.get(`/campaigns/${id}/sequences`),api.get(`/campaigns/${id}/leads`),api.get(`/analytics/daily?campaign_id=${id}&start_date=${from.toISOString().slice(0,10)}&end_date=${new Date().toISOString().slice(0,10)}`)]);
   setData({campaign,inboxes,sequences,leads,daily});setInboxSelection(campaign.inbox_ids||[]);setCalendar({sending_days:campaign.sending_days||[],sending_hours_start:campaign.sending_hours_start,sending_hours_end:campaign.sending_hours_end,timezone:campaign.timezone||'UTC'});return true;
  }catch(e){setError(e);return false;}
 },[id]);
 const check=useCallback(async()=>{setBusy(true);setError('');setReport(null);try{const r=await api.get(`/campaigns/${id}/preflight`);setReport(r);return r;}catch(e){setError(e);return null;}finally{setBusy(false);}},[id]);
 useEffect(()=>{setData(null);setReport(null);load();check();},[id]);
 // On returning from an editor, refresh both values and diagnostics.
 useEffect(()=>{if(data){load();check();}},[tab]);
 const action=async()=>{setBusy(true);setError('');try{
  if(data.campaign.paused){setReport(null);await api.patch(`/campaigns/${id}`,calendar);const r=await api.get(`/campaigns/${id}/preflight`);setReport(r);if(!r.ready){setDetails(true);return;}await api.post(`/campaigns/${id}/start`,{});}
  else await api.post(`/campaigns/${id}/pause`,{});
  await load();
 }catch(e){setError(e);}finally{setBusy(false);}};
 const saveInboxes=async()=>{setBusy(true);setError('');try{await api.patch(`/campaigns/${id}`,{inbox_ids:inboxSelection});const loaded=await load();setReport(null);return loaded;}catch(e){setError(e);return false;}finally{setBusy(false);}};
 const saveCalendar=async()=>{if(!calendar.sending_days.length||!calendar.sending_hours_start||!calendar.sending_hours_end||calendar.sending_hours_start>=calendar.sending_hours_end){setError(new Error(ct("Wybierz dni wysyłki i godzinę końca późniejszą niż początek.")));return false;}setBusy(true);setError('');setSaved('');try{await api.patch(`/campaigns/${id}`,calendar);setSaved('Harmonogram zapisany.');if(!await load())return false;setReport(await api.get(`/campaigns/${id}/preflight`));return true;}catch(e){setError(e);return false;}finally{setBusy(false);}};
 const refreshCampaign=async()=>{const ok=await load();await check();return ok;};
 const nextStep=async()=>{if(busy)return;if(tab==='schedule'&&!await saveCalendar())return;if(tab==='inboxes'&&!await saveInboxes())return;navigate(`?setup=1#${campaignSetupSteps[stepIndex+1][0]}`);};
 if(!data)return <div className="sk-page"><ErrorNotice error={error} onRetry={load}/>{!error&&<Empty>{ct("Wczytywanie kampanii…")}</Empty>}</div>;
 const {campaign:c,sequences,leads,daily}=data,ib=data.inboxes.filter(i=>(c.inbox_ids||[]).includes(i.id)),first=ib[0];
 const blocking=(report?.issues||[]).some(i=>i.severity==='error');
 const campaignState=c.paused?(report?.ready?['green',ct("Gotowa do startu")]:blocking?['red',ct("Wymaga poprawek")]:['amber',ct("Wstrzymana")]):['blue',ct("Aktywna")];
 const preflightTone=report?.ready?'green':report?(blocking?'red':'amber'):'neutral';
 const preflightMessage=report?.ready?ct("Kampania jest gotowa do uruchomienia!"):report?(blocking?ct("Popraw błędy przed uruchomieniem."):ct("Sprawdź ostrzeżenia przed uruchomieniem.")):ct("Sprawdzanie gotowości…");
 const jitterMinutes=first?Math.max(0,Math.round((Number(first.max_jitter_seconds)||0)/60)):'—';
 const groups=[['mail',ct("Skrzynki SMTP"),['no_inboxes','inbox_paused','smtp_missing','smtp_not_verified'],ct('{count} przypisanych skrzynek',{count:ib.length})],['stack',ct("Sekwencja wiadomości"),['no_sequences','first_subject_missing','empty_sequence_body'],ct('{count} kroków',{count:sequences.length})],['contacts',ct("Kontakty"),['no_contacts','no_sendable_contacts','custom_emails_pending'],ct('{count} kwalifikujących się do wysyłki',{count:report?.summary?.sendable_contacts??leads.length})],['template',ct("Zmienne w szablonach"),['missing_variable_values'],ct("Sprawdzenie wartości kontaktów")],['calendar',ct("Harmonogram"),['no_sending_days','invalid_sending_days','invalid_sending_window','invalid_timezone'],ct("Dni, godziny i strefa czasowa")],['clock',ct("Limity wysyłki"),['daily_limit_invalid','hourly_above_daily','hourly_spacing_applied'],ct("Limity skrzynek")],['warning',ct("Potencjalne ryzyka"),[],ct('{count} ostrzeżeń',{count:report?.warnings?.length||0})],['shield',ct("Bezpieczeństwo kolejki"),['uncertain_send_attempts'],ct("Kontrola niepewnych wysyłek")]];
 let cumulative=0;
 return <div className="sk-page sk-campaign-page">
  <div className="sk-breadcrumb"><Link to="/campaigns">{ct("Kampanie")}</Link><Icon name="next" size={13}/><span>{c.name}</span></div>
  <div className="sk-page-heading sk-campaign-heading"><div><div className="sk-title-line"><h1>{c.name}</h1><Badge tone={campaignState[0]} dot>{campaignState[1]}</Badge></div><p>{ct("Wiadomości, odbiorcy i harmonogram kampanii.")}</p></div><div className="sk-heading-actions"><div className="sk-heading-meta"><Icon name="calendar"/><div>{ct("Utworzona")}<small>{dateTime(c.created_at,{},language)}</small></div></div>{!setup&&!['settings','queue'].includes(tab)&&<Button icon={c.paused?'play':'pause'} variant={c.paused?'primary':'outline'} disabled={busy||(setup&&c.paused&&!report?.ready)} onClick={action}>{busy?ct("Proszę czekać…"):c.paused?ct("Uruchom kampanię"):ct("Wstrzymaj")}</Button>}</div></div>
  <ErrorNotice error={error} onRetry={load}/>
  {!setup&&c.paused&&<div className="sk-setup-entry"><Button to={`?setup=1#overview`} icon="check">{ct("Otwórz kreator i podsumowanie")}</Button></div>}
  {setup?<CampaignSetupSteps current={stepIndex} campaignId={id}/>:<nav className="sk-tabs" aria-label={ct("Sekcje kampanii")}>{tabs.map(([key,label])=><Link className={`sk-tab ${tab===key?'active':''}`} aria-current={tab===key?'page':undefined} to={'#'+key} key={key}>{ct(label)}</Link>)}</nav>}
  {setup&&tab==='overview'?<CampaignPreflight campaign={c} inboxes={ib} sequences={sequences} report={report} busy={busy} onCheck={check} onStart={action}/>:setup&&tab==='schedule'?<Panel title={ct("Harmonogram wysyłki")} icon="calendar"><div className="sk-builder-panel-body">
    <div className="sk-builder-days" role="group" aria-label={ct("Dni wysyłki")}>{campaignWeekdays(language).map((day,i)=><label key={day}><input type="checkbox" checked={calendar.sending_days.includes(i)} onChange={()=>setCalendar(p=>({...p,sending_days:p.sending_days.includes(i)?p.sending_days.filter(d=>d!==i):[...p.sending_days,i].sort()}))}/>{day}</label>)}</div>
    <div className="sk-builder-two-col"><label>{ct("Początek wysyłki")}<input type="time" value={calendar.sending_hours_start} onChange={e=>setCalendar(p=>({...p,sending_hours_start:e.target.value}))}/></label><label>{ct("Koniec wysyłki")}<input type="time" value={calendar.sending_hours_end} onChange={e=>setCalendar(p=>({...p,sending_hours_end:e.target.value}))}/></label></div>
    <label>{ct("Strefa czasowa")}<select value={calendar.timezone} onChange={e=>setCalendar(p=>({...p,timezone:e.target.value}))}>{[...new Set([calendar.timezone,'UTC',...(Intl.supportedValuesOf?.('timeZone')||[])])].map(t=><option key={t}>{t}</option>)}</select></label>
    <Button onClick={saveCalendar} disabled={busy}>{ct("Zapisz harmonogram")}</Button><span role="status">{ct(saved)}</span>
   </div></Panel>:tab==='overview'?<>
   <div className="sk-metrics four"><Metric icon="send" title={ct("Kontakty w kampanii")} value={leads.length} detail={ct("Odbiorcy tej kampanii")}/><Metric icon="mail" tone="blue" title={ct("Skrzynki nadawcze")} value={ib.length} detail={ct('{count} aktywnych',{count:ib.filter(i=>!i.paused).length})}/><Metric icon="reply" tone="purple" title={ct("Odpowiedzi")} value={c.stats?.replies??0} detail={ct("Rzeczywiste wyniki kampanii")}/><Metric icon="chart" title={ct("Status kampanii")} value={<span className="sk-campaign-status-value">{campaignState[1]}</span>} detail={ct("Kontrola przed uruchomieniem")}/></div>
   <div className="sk-campaign-grid"><div>
    <Panel title={ct("Harmonogram wysyłki")} icon="calendar"><div className="sk-schedule-form">
     <div className="sk-schedule-row"><label>{ct("Dni wysyłki")}</label><div className="sk-days">{campaignWeekdays(language).map((l,i)=><label key={i}><input type="checkbox" checked={calendar.sending_days.includes(i)} onChange={()=>setCalendar(p=>({...p,sending_days:p.sending_days.includes(i)?p.sending_days.filter(d=>d!==i):[...p.sending_days,i]}))}/>{l}</label>)}</div></div>
     <div className="sk-schedule-row"><label>{ct("Godziny wysyłki")}</label><div className="sk-time-range"><input aria-label={ct("Początek wysyłki")} type="time" value={calendar.sending_hours_start} onChange={e=>setCalendar(p=>({...p,sending_hours_start:e.target.value}))}/><span>–</span><input aria-label={ct("Koniec wysyłki")} type="time" value={calendar.sending_hours_end} onChange={e=>setCalendar(p=>({...p,sending_hours_end:e.target.value}))}/></div></div>
     <div className="sk-schedule-row"><label htmlFor="campaign-tz">{ct("Strefa czasowa")}</label><select id="campaign-tz" value={calendar.timezone} onChange={e=>setCalendar(p=>({...p,timezone:e.target.value}))}>{[...new Set([calendar.timezone,'UTC',...(Intl.supportedValuesOf?.('timeZone')||[])])].map(t=><option key={t}>{t}</option>)}</select></div>
     <dl className="sk-mailbox-limits">{[[ct("Dzienny limit na skrzynkę"),first?.max_emails_per_day,ct("wiadomości")],[ct("Godzinowy limit na skrzynkę"),first?.max_emails_per_hour||'—',ct("wiadomości")],[ct("Minimalny odstęp"),first?.wait_minutes_between,ct("minut")],[ct("Losowe opóźnienie"),first?'0–'+jitterMinutes:'—',ct("minut")]].map(([label,value,unit])=><div key={label}><dt>{label}</dt><dd><strong>{value??'—'}</strong> {unit}</dd></div>)}</dl>
     <div className="sk-form-actions sk-form-actions-between"><span className="sk-small sk-muted">{saved?ct(saved):first?.email||ct("Brak skrzynki")}</span><Button className="compact" disabled={busy} onClick={saveCalendar}>{ct("Zapisz harmonogram")}</Button></div>
    </div></Panel>
    <Panel title={ct("Sekwencja wiadomości")} icon="mail" action={<Button icon="edit" className="compact" to="#sequences">{ct("Edytuj sekwencję")}</Button>}><div className="sk-sequence-list">{sequences.map((s,i)=>{cumulative+=s.wait_days_after_previous||0;return <div className="sk-sequence-step" key={s.id}><span className="sk-step-number">{i+1}</span><div className="sk-sequence-copy"><strong>{i===0?ct("Pierwsza wiadomość"):ct('Ponowienie #{step}',{step:i})}</strong><small>{ct("Temat:")} {s.subject||ct("Odpowiedź w wątku")}</small><small>{plain(s.body||s.fallback_body)}</small></div><Badge tone="blue">{ct("Dzień")} {cumulative}</Badge><Button className="compact" to="#sequences" icon="edit">{ct("Edytuj")}</Button></div>})}{!sequences.length&&<Empty>{ct("Dodaj pierwszą wiadomość.")}</Empty>}<Button to="#sequences" className="sk-full-width compact" icon="plus">{ct("Dodaj kolejny krok")}</Button></div></Panel>
   </div><div>
    <div className="sk-preflight"><div className="sk-panel-heading"><h2><Icon name="shield"/>{ct("Pre-flight — sprawdź przed startem")}</h2><Button icon="refresh" variant="ghost" className="compact" onClick={check} disabled={busy}>{ct("Sprawdź ponownie")}</Button></div><div className="sk-preflight-rows">{groups.map(([icon,title,codes,desc])=>{const issues=icon==='warning'?report?.warnings||[]:(report?.issues||[]).filter(i=>codes.includes(i.code));const severe=issues.some(i=>i.severity==='error'),tone=severe?'red':issues.length?'amber':'green';return <div className="sk-preflight-row" key={title}><Icon name={icon} size={22}/><div><strong>{title}</strong><small>{issues.length?issues[0].message:desc}</small></div><Badge tone={report?tone:'neutral'}><Icon name={!report?'clock':issues.length?'warning':'check'} size={16}/></Badge><Button className="compact" onClick={()=>setDetails(v=>!v)}>{ct("Szczegóły")}</Button></div>})}<div className={`sk-notice tone-${preflightTone}`}><Icon name={report?.ready?'success':'warning'} size={25}/><span><strong>{preflightMessage}</strong><br/>{ct("Wysyłka rozpoczyna się po ręcznym uruchomieniu.")}</span></div></div></div>
    {details&&<Panel title={ct("Szczegóły kontroli")} icon="info"><div className="sk-panel-body-compact">{!report?<p className="sk-muted sk-small">{ct("Brak aktualnych wyników kontroli.")}</p>:!(report.issues||[]).length?<p className="sk-muted sk-small">{ct("Brak zgłoszonych problemów.")}</p>:(report.issues||[]).map((x,i)=><div className={`sk-notice tone-${x.severity==='error'?'red':'amber'}`} key={i}>{x.message}</div>)}<Button to="#settings" className="compact">{ct("Ustawienia i obsługa błędów")}</Button></div></Panel>}
    <Panel title={ct("Prognoza i statystyki")} icon="chart" action={<Badge>{ct("Ostatnie 7 dni")}</Badge>}><div className="sk-campaign-stats">{[['send',c.stats?.scheduled||0,ct("W kolejce")],['mail',c.stats?.emails_sent||0,ct("Wysłano")],['reply',c.stats?.replies||0,ct("Odpowiedzi")],['contacts',leads.length,ct("Kontakty")]].map(([icon,value,label])=><div key={label}><strong><Icon name={icon}/>{value}</strong><small>{label}</small></div>)}</div><ActivityChart rows={daily}/></Panel>
   </div></div>
  </>:tab==='inboxes'?<Panel title={ct("Skrzynki przypisane do kampanii")} icon="mail"><div className="sk-builder-panel-body">{setup&&<><div className="sk-builder-mailbox-list">{data.inboxes.map(i=><label className="sk-builder-mailbox" key={i.id}><input type="checkbox" checked={inboxSelection.includes(i.id)} onChange={e=>setInboxSelection(old=>e.target.checked?[...old,i.id]:old.filter(x=>x!==i.id))}/><span className="sk-builder-mailbox-copy"><strong>{i.email}</strong><small>{i.paused?ct("Wstrzymana"):ct("Aktywna")} {ct("· limit:")} {i.max_emails_per_day}{ct("/dzień")}</small></span></label>)}</div><Button onClick={saveInboxes} disabled={busy}>{ct("Zapisz skrzynki")}</Button><Button to="/inboxes">{ct("Zarządzaj skrzynkami")}</Button></>}<div className="sk-table-wrap"><table className="sk-table"><thead><tr><th>{ct("Skrzynka")}</th><th>{ct("Limit dzienny")}</th><th>{ct("Limit godzinowy")}</th><th>{ct("Odstęp")}</th><th></th></tr></thead><tbody>{ib.map(i=><tr key={i.id}><td>{i.email}</td><td>{i.max_emails_per_day}</td><td>{i.max_emails_per_hour||ct("Brak")}</td><td>{i.wait_minutes_between} {ct("min")}</td><td><Button to={'/inboxes?inbox='+i.id} className="compact">{ct("Ustawienia skrzynki")}</Button></td></tr>)}</tbody></table>{!ib.length&&<Empty icon="mail">{ct("Ta kampania nie ma jeszcze przypisanej skrzynki.")}</Empty>}<Button to="#settings" className="compact sk-top-gap">{ct("Zmień przypisanie")}</Button></div></div></Panel>:tab==='settings'?<CampaignSettings key={id} campaign={c} inboxes={data.inboxes} onSaved={refreshCampaign}/>:tab==='queue'?<CampaignActivity key={id} campaign={c} inboxes={data.inboxes} contact={new URLSearchParams(location.search).get('contact')||''} onSaved={refreshCampaign}/>:<div className="sk-legacy-campaign"><CampaignDetail key={`${id}:${tab}`} embedded onQueueContact={email=>navigate(`?contact=${encodeURIComponent(email)}#queue`)}/></div>}
  {setup&&<div className="sk-setup-footer"><Button to={`/campaigns/${id}#overview`}>{ct("Zakończ później")}</Button><span className="sk-muted sk-small">{ct("Zapisz zmiany w bieżącym etapie przed przejściem dalej.")}</span>{stepIndex>0&&<Button to={`?setup=1#${campaignSetupSteps[stepIndex-1][0]}`} icon="back">{ct("Wstecz")}</Button>}{stepIndex<5&&<Button onClick={nextStep} disabled={busy} variant="primary" icon="next">{tab==='schedule'||tab==='inboxes'?ct("Zapisz i dalej"):ct("Dalej")}</Button>}</div>}
 </div>;
}
