import {useState,useEffect,useMemo,useRef,useCallback} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {api} from '../../api';
import {useNotify} from '../../context/NotificationContext';
import {useConfirm} from '../../context/ConfirmContext';
import {useAuth} from '../../context/AuthContext';
import {Button,Badge,Avatar,Icon,Empty,ErrorNotice,ContactStatus,dateTime} from '../ui';
import Modal from '../Modal';
import FieldManager,{FieldInput} from '../FieldManager';
import ContactImport from '../ContactImport';

const baseColumns=[{id:'name',label:'Nazwa / imię'},{id:'email',label:'E-mail'},{id:'status',label:'Status'},{id:'campaigns',label:'Kampanie'},{id:'created_at',label:'Dodano'}];
export default function Contacts(){
 const notify=useNotify(),confirm=useConfirm(),{user}=useAuth();const [params]=useSearchParams();
 const prefKey=`sekaro.contacts.columns.${user?.id||'local'}`;
 const [leads,setLeads]=useState([]),[fields,setFields]=useState([]),[lists,setLists]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [search,setSearch]=useState(''),[query,setQuery]=useState(''),[list,setList]=useState(''),[status,setStatus]=useState(''),[page,setPage]=useState(1),[selected,setSelected]=useState(new Set());
 const [drawer,setDrawer]=useState(params.get('fields')==='1'),[columnMenu,setColumnMenu]=useState(false),[modal,setModal]=useState(null),[file,setFile]=useState(null),[busy,setBusy]=useState(false),[formError,setFormError]=useState('');
 const [newContact,setNewContact]=useState({email:'',name:'',custom_data:{}}),[campaigns,setCampaigns]=useState([]),[campaignId,setCampaignId]=useState('');
 const [fieldFilter,setFieldFilter]=useState({key:'',value:''}),[hidden,setHidden]=useState(()=>{try{return new Set(JSON.parse(localStorage.getItem(prefKey)||localStorage.getItem('sekaro.contacts.hiddenColumns')||'["campaigns","created_at"]'));}catch{return new Set(['campaigns','created_at']);}});
 const [suppression,setSuppression]=useState([]),[blockEmail,setBlockEmail]=useState('');
 const fileRef=useRef(null),columnRef=useRef(null),requestRef=useRef(0);
 const refreshFields=useCallback(async()=>{const f=await api.get('/contact-fields');setFields(f);},[]);
 const reload=useCallback(async()=>{const seq=++requestRef.current;setLoading(true);setError('');try{
  const q=new URLSearchParams();if(query)q.set('q',query);if(list)q.set('list_id',list);if(status)q.set('status',status);
  const [rows,f,l]=await Promise.all([api.get('/leads?'+q),api.get('/contact-fields'),api.get('/leads/lists')]);if(seq===requestRef.current){setLeads(rows);setFields(f);setLists(l);}
 }catch(e){if(seq===requestRef.current)setError(e);}finally{if(seq===requestRef.current)setLoading(false);}},[query,list,status]);
 useEffect(()=>{reload();return()=>{requestRef.current++;};},[reload]);
 useEffect(()=>{const t=setTimeout(()=>setQuery(search.trim()),250);return()=>clearTimeout(t);},[search]);
 useEffect(()=>{setPage(1);setSelected(new Set());},[query,list,status,fieldFilter]);
 useEffect(()=>{if(!columnMenu)return;const handle=e=>{if(e.key==='Escape'||(e.type==='pointerdown'&&!columnRef.current?.contains(e.target)))setColumnMenu(false);};document.addEventListener('pointerdown',handle);document.addEventListener('keydown',handle);return()=>{document.removeEventListener('pointerdown',handle);document.removeEventListener('keydown',handle);};},[columnMenu]);
 const columns=useMemo(()=>[...baseColumns,...fields.filter(f=>!f.system).map(f=>({id:'custom:'+f.key,key:f.key,label:f.label||f.key,field_type:f.field_type}))],[fields]);
 const visible=columns.filter(c=>c.id==='email'||!hidden.has(c.id));
 const filtered=useMemo(()=>!fieldFilter.key?leads:leads.filter(l=>String(l.custom_data?.[fieldFilter.key]??'').toLocaleLowerCase().includes(fieldFilter.value.toLocaleLowerCase())),[leads,fieldFilter]);
 const pages=Math.max(1,Math.ceil(filtered.length/10)),current=Math.min(page,pages),rows=filtered.slice((current-1)*10,current*10);
 const toggleColumn=id=>{setHidden(prev=>{const next=new Set(prev);next.has(id)?next.delete(id):next.add(id);try{localStorage.setItem(prefKey,JSON.stringify([...next]));}catch{}return next;});};
 const toggle=id=>setSelected(prev=>{const next=new Set(prev);next.has(id)?next.delete(id):next.add(id);return next;});
 const selectPage=()=>setSelected(prev=>{const next=new Set(prev),all=rows.every(l=>prev.has(l.id));rows.forEach(l=>all?next.delete(l.id):next.add(l.id));return next;});
 const openModal=type=>{setFormError('');setModal(type);};
 const exportContacts=async()=>{try{const q=new URLSearchParams();if(query)q.set('q',query);if(list)q.set('list_id',list);if(status)q.set('status',status);const r=await api.download('/leads/export?'+q);const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download='sekaro-kontakty.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(e);}};
 const create=async e=>{e.preventDefault();setBusy(true);setFormError('');try{await api.post('/ui/contacts',newContact);setModal(null);setNewContact({email:'',name:'',custom_data:{}});notify({type:'success',message:'Kontakt utworzony. Nie został dodany do kampanii.'});await reload();}catch(e){setFormError(e);}finally{setBusy(false);}};
 const remove=async()=>{if(!selected.size||!await confirm(`Usunąć ${selected.size} wybranych kontaktów wraz z ich historią? Tej operacji nie można cofnąć.`))return;setBusy(true);try{await api.post('/leads/bulk-delete',{lead_ids:[...selected]});setSelected(new Set());await reload();}catch(e){setError(e);}finally{setBusy(false);}};
 const openCampaigns=async()=>{try{setCampaigns(await api.get('/campaigns'));setCampaignId('');openModal('campaign');}catch(e){setError(e);}};
 const enroll=async()=>{const c=campaigns.find(c=>String(c.id)===campaignId);if(!c)return;
  if(!c.paused&&!await confirm('Ta kampania jest aktywna. Dodane kontakty mogą wejść do kolejki wysyłki. Kontynuować?'))return;
  setBusy(true);setFormError('');try{const result=await api.post(`/campaigns/${c.id}/leads`,leads.filter(l=>selected.has(l.id)).map(l=>({email:l.email,name:l.name,custom_data:l.custom_data})));setModal(null);setSelected(new Set());notify({type:'success',message:`Przypisanie zakończone. Dodano: ${result.added||0}, wykluczone: ${result.suppressed||0}.`});await reload();}catch(e){setFormError(e);}finally{setBusy(false);}
 };
 const openSuppression=async()=>{try{setSuppression(await api.get('/leads/suppression'));openModal('suppression');}catch(e){setError(e);}};
 const addBlock=async e=>{e.preventDefault();setBusy(true);setFormError('');try{await api.post('/leads/suppression',{email:blockEmail,reason:'manual',source:'manual'});setBlockEmail('');setSuppression(await api.get('/leads/suppression'));}catch(e){setFormError(e);}finally{setBusy(false);}};
 const removeBlock=async x=>{if(!await confirm(`Usunąć ${x.email} z globalnej listy wykluczeń? Nie usuwa to statusów wypisania w kampaniach.`))return;setBusy(true);try{await api.del('/leads/suppression/'+x.id);setSuppression(await api.get('/leads/suppression'));}catch(e){setFormError(e);}finally{setBusy(false);}};
 const renderCell=(lead,column)=>{if(column.key){const value=lead.custom_data?.[column.key];if(value==null||value==='')return <span className="sk-muted">—</span>;const text=typeof value==='object'?JSON.stringify(value):String(value);return column.field_type==='select'?<Badge tone="blue">{text}</Badge>:<span title={text} className="sk-contact-value">{text}</span>;}
  if(column.id==='name')return <Link className="sk-inline-contact" to={'/leads/'+lead.id}><Avatar size="small" name={lead.name||lead.email}/><span>{lead.name||'—'}</span></Link>;
  if(column.id==='email')return <Link to={'/leads/'+lead.id}>{lead.email}</Link>;
  if(column.id==='status')return <ContactStatus lead={lead}/>;
  if(column.id==='created_at')return dateTime(lead.created_at);
  return (lead.campaigns||[]).length?<span>{lead.campaigns.map((c,i)=><Link key={c.campaign_id} to={'/campaigns/'+c.campaign_id}>{i>0?', ':''}{c.campaign_name}</Link>)}</span>:'—';
 };
 return <div className={`sk-contact-layout ${drawer?'with-drawer':''}`}>
  <div className="sk-contacts-content"><div className="sk-breadcrumb"><Link to="/leads">Kontakty</Link><Icon name="next" size={13}/><span>{list?lists.find(l=>String(l.id)===list)?.name:'Wszystkie kontakty'}</span></div>
   <div className="sk-page-heading"><div><h1>Kontakty</h1><p>Zarządzaj swoją bazą kontaktów i niestandardowymi polami.</p></div><div className="sk-heading-actions"><div className="sk-heading-meta"><Icon name="contacts" size={24}/><div><strong style={{color:'var(--sk-text)',fontSize:16}}>{filtered.length.toLocaleString('pl-PL')}</strong><small className="sk-muted">kontaktów w widoku</small></div></div></div></div>
   <ErrorNotice error={error} onRetry={reload}/>
   <div className="sk-toolbar"><Button variant="primary" icon="plus" onClick={()=>openModal('contact')}>Dodaj kontakt</Button><Button icon="upload" onClick={()=>fileRef.current?.click()}>Importuj CSV/XLSX</Button><Button icon="settings" onClick={()=>setDrawer(v=>!v)} aria-expanded={drawer}>Zarządzaj polami</Button>
    <div className="sk-popover-container" ref={columnRef}><Button icon="eye" onClick={()=>setColumnMenu(v=>!v)} aria-expanded={columnMenu}>Widoczne kolumny</Button>{columnMenu&&<div className="sk-popover"><h3>Widoczne kolumny</h3><div className="sk-scroll">{columns.map(c=><label key={c.id}><input type="checkbox" checked={c.id==='email'||!hidden.has(c.id)} disabled={c.id==='email'} onChange={()=>toggleColumn(c.id)}/><span>{c.label}</span></label>)}</div><Button variant="ghost" onClick={()=>{setHidden(new Set());try{localStorage.setItem(prefKey,'[]');}catch{}}}>Pokaż wszystkie</Button></div>}</div>
    <input type="file" accept=".csv,.xlsx,.xlsm" ref={fileRef} style={{display:'none'}} onChange={e=>{if(e.target.files[0])setFile(e.target.files[0]);e.target.value='';}}/>
   </div>
   {params.get('import')&&<p className="sk-small sk-muted" style={{marginTop:10}}>Kliknij „Importuj CSV/XLSX”, aby wybrać plik z komputera.</p>}
   <div className="sk-filters"><div className="sk-search-input"><Icon name="search" size={19}/><input aria-label="Szukaj kontaktów" placeholder="Szukaj kontaktów (e-mail lub nazwa)…" value={search} onChange={e=>setSearch(e.target.value)}/></div><select aria-label="Status kontaktów" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Status: Wszystkie</option><option value="active">Aktywny</option><option value="replied">Odpowiedział</option><option value="bounced">Odbicie</option><option value="unsubscribed">Wypisany</option></select><select aria-label="Lista kontaktów" value={list} onChange={e=>setList(e.target.value)}><option value="">Listy: Wszystkie</option>{lists.map(l=><option key={l.id} value={l.id}>{l.name} ({l.member_count})</option>)}</select><Button icon="filter" className="compact" onClick={()=>openModal('filters')}>Więcej filtrów</Button></div>
   {fieldFilter.key&&<div className="sk-toolbar" style={{marginBottom:10}}><Badge tone="blue">{fieldFilter.key}: {fieldFilter.value}</Badge><Button variant="ghost" onClick={()=>setFieldFilter({key:'',value:''})}>Wyczyść filtr</Button></div>}
   <div className="sk-table-wrap sk-contacts-table"><table className="sk-table"><thead><tr><th><input type="checkbox" aria-label="Zaznacz kontakty na stronie" checked={rows.length>0&&rows.every(l=>selected.has(l.id))} onChange={selectPage}/></th>{visible.map(c=><th key={c.id}>{c.label}</th>)}<th aria-label="Akcje"/></tr></thead><tbody>{rows.map(l=><tr key={l.id} className={selected.has(l.id)?'is-selected':''}><td><input type="checkbox" aria-label={`Zaznacz ${l.email}`} checked={selected.has(l.id)} onChange={()=>toggle(l.id)}/></td>{visible.map(c=><td key={c.id}>{renderCell(l,c)}</td>)}<td><Link to={'/leads/'+l.id} className="sk-icon-button" aria-label={`Otwórz ${l.email}`}><Icon name="more" size={18}/></Link></td></tr>)}</tbody></table>{!rows.length&&<Empty icon="contacts">{loading?'Wczytywanie kontaktów…':'Brak kontaktów spełniających warunki.'}</Empty>}</div>
   <div className="sk-table-footer"><div className="sk-toolbar"><span>{selected.size} zaznaczonych</span><Button className="compact" disabled={!selected.size||busy} onClick={openCampaigns}>Dodaj do kampanii</Button><Button className="compact" icon="delete" disabled={!selected.size||busy} onClick={remove}>Usuń</Button><Button className="compact" icon="download" onClick={exportContacts} disabled={!!fieldFilter.key} title={fieldFilter.key?'Eksport obsługuje listę, status i wyszukiwanie. Wyczyść filtr pola, aby wyeksportować.':undefined}>Eksport</Button></div><div className="sk-pagination"><button aria-label="Poprzednia strona" disabled={current===1} onClick={()=>setPage(p=>p-1)}><Icon name="prev" size={17}/></button>{Array.from({length:Math.min(5,pages)},(_,i)=>Math.min(Math.max(1,current-2),Math.max(1,pages-4))+i).map(p=><button className={p===current?'active':''} key={p} onClick={()=>setPage(p)}>{p}</button>)}{pages>5&&<span> / {pages}</span>}<button aria-label="Następna strona" disabled={current===pages} onClick={()=>setPage(p=>p+1)}><Icon name="next" size={17}/></button></div></div>
   <div className="sk-toolbar" style={{marginTop:12,justifyContent:'space-between'}}><Button variant="ghost" icon="block" onClick={openSuppression}>Lista wykluczeń</Button><Link className="sk-small sk-muted" to="/contacts-tools">Odzyskiwanie odbić i dodatkowe narzędzia</Link></div>
  </div>
  {drawer&&<FieldManager fields={fields} onRefresh={async()=>{await refreshFields();await reload();}} onClose={()=>setDrawer(false)}/>}
  {file&&<ContactImport file={file} onClose={()=>setFile(null)} onDone={reload}/>}
  {modal==='contact'&&<Modal title="Dodaj kontakt" onClose={()=>setModal(null)} busy={busy}><ErrorNotice error={formError}/><form onSubmit={create}><div className="sk-form"><label>E-mail<input required type="email" autoComplete="off" value={newContact.email} onChange={e=>setNewContact(p=>({...p,email:e.target.value}))}/></label><label>Nazwa / imię<input value={newContact.name} maxLength={255} onChange={e=>setNewContact(p=>({...p,name:e.target.value}))}/></label>{fields.filter(f=>!f.system).map(f=><label key={f.key}>{f.label}<FieldInput field={f} value={newContact.custom_data[f.key]} onChange={v=>setNewContact(p=>({...p,custom_data:{...p.custom_data,[f.key]:v}}))}/></label>)}</div><p className="sk-small sk-muted" style={{marginTop:15}}>Zapisanie kontaktu nie uruchamia wysyłki.</p><div className="sk-form-actions"><Button onClick={()=>setModal(null)} disabled={busy}>Anuluj</Button><Button type="submit" variant="primary" disabled={busy}>{busy?'Zapisywanie…':'Utwórz kontakt'}</Button></div></form></Modal>}
  {modal==='campaign'&&<Modal title="Dodaj kontakty do kampanii" onClose={()=>setModal(null)} small busy={busy}><ErrorNotice error={formError}/><p className="sk-small sk-muted">Wybrano {selected.size} kontaktów. Lista wykluczeń pozostaje aktywna.</p><label className="sk-form" style={{gridTemplateColumns:'1fr'}}>Kampania<select value={campaignId} onChange={e=>setCampaignId(e.target.value)}><option value="">Wybierz kampanię</option>{campaigns.map(c=><option key={c.id} value={c.id}>{c.name} · {c.paused?'wstrzymana':'aktywna'}</option>)}</select></label><div className="sk-form-actions"><Button onClick={()=>setModal(null)}>Anuluj</Button><Button variant="primary" disabled={!campaignId||busy} onClick={enroll}>Dodaj do kampanii</Button></div></Modal>}
  {modal==='filters'&&<Modal title="Filtruj według własnego pola" onClose={()=>setModal(null)} small><div className="sk-form" style={{gridTemplateColumns:'1fr'}}><label>Pole<select value={fieldFilter.key} onChange={e=>setFieldFilter(p=>({...p,key:e.target.value}))}><option value="">Bez filtra</option>{fields.filter(f=>!f.system).map(f=><option key={f.key} value={f.key}>{f.label}</option>)}</select></label><label>Zawiera<input value={fieldFilter.value} onChange={e=>setFieldFilter(p=>({...p,value:e.target.value}))}/></label></div><div className="sk-form-actions"><Button variant="primary" onClick={()=>setModal(null)}>Zastosuj</Button></div></Modal>}
  {modal==='suppression'&&<Modal title="Globalna lista wykluczeń" onClose={()=>setModal(null)} busy={busy}><ErrorNotice error={formError}/><p className="sk-small sk-muted">Adresy z tej listy są blokowane podczas importu i wysyłki.</p><form onSubmit={addBlock} className="sk-toolbar" style={{margin:'16px 0'}}><input required type="email" aria-label="Adres do wykluczenia" placeholder="Adres e-mail" value={blockEmail} onChange={e=>setBlockEmail(e.target.value)}/><Button type="submit" icon="plus" disabled={busy}>Dodaj adres</Button></form><div className="sk-table-wrap"><table className="sk-table"><thead><tr><th>E-mail</th><th>Powód</th><th>Dodano</th><th/></tr></thead><tbody>{suppression.map(x=><tr key={x.id}><td>{x.email}</td><td>{x.reason==='unsubscribe'?'Wypisanie':x.reason==='manual'?'Ręcznie':x.reason}</td><td>{dateTime(x.created_at)}</td><td><Button className="compact" disabled={busy} onClick={()=>removeBlock(x)}>Usuń blokadę</Button></td></tr>)}</tbody></table></div></Modal>}
 </div>;
}
