import {useUiLanguage} from '../../context/LanguageContext';
import {useState,useEffect,useMemo,useRef,useCallback} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {api} from '../../api';
import {useNotify} from '../../context/NotificationContext';
import {useConfirm} from '../../context/ConfirmContext';
import {useAuth} from '../../context/AuthContext';
import {Button,Badge,Avatar,Icon,Empty,ErrorNotice,ContactStatus,dateTime} from '../ui';
import Modal from '../Modal';
import FieldManager,{FieldInput} from '../FieldManager';
import ContactImport from '../ContactImport';

export default function Contacts(){
 const {t,language}=useUiLanguage();
 const notify=useNotify(),confirm=useConfirm(),{user}=useAuth();const [params]=useSearchParams();
 const prefKey=`sekaro.contacts.columns.${user?.id||'local'}`;
 const [leads,setLeads]=useState([]),[fields,setFields]=useState([]),[lists,setLists]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [scope,setScope]=useState('current');
 const [search,setSearch]=useState(''),[query,setQuery]=useState(''),[list,setList]=useState(''),[status,setStatus]=useState(''),[page,setPage]=useState(1),[selected,setSelected]=useState(new Set());
 const [drawer,setDrawer]=useState(params.get('fields')==='1'),[columnMenu,setColumnMenu]=useState(false),[modal,setModal]=useState(null),[file,setFile]=useState(null),[busy,setBusy]=useState(false),[formError,setFormError]=useState('');
 const [newContact,setNewContact]=useState({email:'',name:'',custom_data:{}}),[campaigns,setCampaigns]=useState([]),[campaignId,setCampaignId]=useState('');
 const [filterDraft,setFilterDraft]=useState({key:'',value:''});
 const [fieldFilter,setFieldFilter]=useState({key:'',value:''}),[hidden,setHidden]=useState(()=>{try{return new Set(JSON.parse(localStorage.getItem(prefKey)||localStorage.getItem('sekaro.contacts.hiddenColumns')||'["campaigns","created_at"]'));}catch{return new Set(['campaigns','created_at']);}});
 const [suppression,setSuppression]=useState([]),[blockEmail,setBlockEmail]=useState('');
 const fileRef=useRef(null),columnRef=useRef(null),requestRef=useRef(0);
 const refreshFields=useCallback(async()=>{const f=await api.get('/contact-fields');setFields(f);},[]);
 const reload=useCallback(async()=>{const seq=++requestRef.current;setLoading(true);setError('');try{
  const q=new URLSearchParams();if(scope!=='current')q.set('scope',scope);if(query)q.set('q',query);if(list)q.set('list_id',list);if(status)q.set('status',status);
  const [rows,f,l]=await Promise.all([api.get('/leads?'+q),api.get('/contact-fields'),api.get('/leads/lists')]);if(seq===requestRef.current){setLeads(rows);setFields(f);setLists(l);}
 }catch(e){if(seq===requestRef.current)setError(e);}finally{if(seq===requestRef.current)setLoading(false);}},[query,list,status,scope]);
 useEffect(()=>{reload();return()=>{requestRef.current++;};},[reload]);
 useEffect(()=>{const t=setTimeout(()=>setQuery(search.trim()),250);return()=>clearTimeout(t);},[search]);
 useEffect(()=>{setPage(1);setSelected(new Set());},[query,list,status,fieldFilter,scope]);
 useEffect(()=>{if(!columnMenu)return;const handle=e=>{if(e.key==='Escape'||(e.type==='pointerdown'&&!columnRef.current?.contains(e.target)))setColumnMenu(false);};document.addEventListener('pointerdown',handle);document.addEventListener('keydown',handle);return()=>{document.removeEventListener('pointerdown',handle);document.removeEventListener('keydown',handle);};},[columnMenu]);
 const columns=useMemo(()=>[{id:'name',label:t('contacts.name')},{id:'email',label:t('contacts.email')},{id:'status',label:t('contacts.status')},{id:'campaigns',label:t('contacts.campaigns')},{id:'created_at',label:t('contacts.added')},...fields.filter(f=>!f.system).map(f=>({id:'custom:'+f.key,key:f.key,label:f.label||f.key,field_type:f.field_type}))],[fields,t]);
 const visible=columns.filter(c=>c.id==='email'||!hidden.has(c.id));
 const filtered=useMemo(()=>!fieldFilter.key?leads:leads.filter(l=>String(l.custom_data?.[fieldFilter.key]??'').toLocaleLowerCase().includes(fieldFilter.value.toLocaleLowerCase())),[leads,fieldFilter]);
 const fieldFilterLabel=fields.find(f=>f.key===fieldFilter.key)?.label||fieldFilter.key;
 const pages=Math.max(1,Math.ceil(filtered.length/10)),current=Math.min(page,pages),rows=filtered.slice((current-1)*10,current*10);
 const toggleColumn=id=>{setHidden(prev=>{const next=new Set(prev);next.has(id)?next.delete(id):next.add(id);try{localStorage.setItem(prefKey,JSON.stringify([...next]));}catch{}return next;});};
 const toggle=id=>setSelected(prev=>{const next=new Set(prev);next.has(id)?next.delete(id):next.add(id);return next;});
 const selectPage=()=>setSelected(prev=>{const next=new Set(prev),all=rows.every(l=>prev.has(l.id));rows.forEach(l=>all?next.delete(l.id):next.add(l.id));return next;});
 const openModal=type=>{setFormError('');setModal(type);};
 const exportContacts=async()=>{try{const q=new URLSearchParams();if(scope!=='current')q.set('scope',scope);if(query)q.set('q',query);if(list)q.set('list_id',list);if(status)q.set('status',status);const r=await api.download('/leads/export?'+q);const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download='sekaro-kontakty.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(e);}};
 const create=async e=>{e.preventDefault();setBusy(true);setFormError('');try{await api.post('/ui/contacts',newContact);setModal(null);setNewContact({email:'',name:'',custom_data:{}});notify({type:'success',message:t('contacts.created')});await reload();}catch(e){setFormError(e);}finally{setBusy(false);}};
 const remove=async()=>{if(!selected.size||!await confirm({message:t('contacts.deleteWarning',{count:selected.size}),danger:true}))return;setBusy(true);try{await api.post('/leads/bulk-delete',{lead_ids:[...selected]});setSelected(new Set());await reload();}catch(e){setError(e);}finally{setBusy(false);}};
 const archive=async archived=>{if(!selected.size||!await confirm(t(archived?'contacts.archiveWarning':'contacts.restoreWarning',{count:selected.size})))return;setBusy(true);try{await api.post('/leads/archive',{lead_ids:[...selected],archived});setSelected(new Set());await reload();}catch(e){setError(e);}finally{setBusy(false);}};
 const openCampaigns=async()=>{try{setCampaigns(await api.get('/campaigns'));setCampaignId('');openModal('campaign');}catch(e){setError(e);}};
 const enroll=async()=>{const c=campaigns.find(c=>String(c.id)===campaignId);if(!c)return;
  if(!c.paused&&!await confirm(t('contacts.activeWarning')))return;
  setBusy(true);setFormError('');try{const result=await api.post(`/campaigns/${c.id}/leads`,leads.filter(l=>selected.has(l.id)).map(l=>({email:l.email,name:l.name,custom_data:l.custom_data})));setModal(null);setSelected(new Set());notify({type:'success',message:t('contacts.enrolledResult',{added:result.added||0,suppressed:result.suppressed||0})});await reload();}catch(e){setFormError(e);}finally{setBusy(false);}
 };
 const openSuppression=async()=>{try{setSuppression(await api.get('/leads/suppression'));openModal('suppression');}catch(e){setError(e);}};
 const addBlock=async e=>{e.preventDefault();setBusy(true);setFormError('');try{await api.post('/leads/suppression',{email:blockEmail,reason:'manual',source:'manual'});setBlockEmail('');setSuppression(await api.get('/leads/suppression'));}catch(e){setFormError(e);}finally{setBusy(false);}};
 const removeBlock=async x=>{if(!await confirm({message:t('contacts.removeBlockWarning',{email:x.email}),danger:true}))return;setBusy(true);try{await api.del('/leads/suppression/'+x.id);setSuppression(await api.get('/leads/suppression'));}catch(e){setFormError(e);}finally{setBusy(false);}};
 const renderCell=(lead,column)=>{if(column.key){const value=lead.custom_data?.[column.key];if(value==null||value==='')return <span className="sk-muted">—</span>;const text=typeof value==='object'?JSON.stringify(value):String(value);return column.field_type==='select'?<Badge tone="blue">{text}</Badge>:<span title={text} className="sk-contact-value">{text}</span>;}
  if(column.id==='name')return <Link className="sk-inline-contact" to={'/leads/'+lead.id}><Avatar size="small" name={lead.name||lead.email}/><span>{lead.name||'—'}</span></Link>;
  if(column.id==='email')return <Link to={'/leads/'+lead.id}>{lead.email}</Link>;
  if(column.id==='status')return <ContactStatus lead={lead}/>;
  if(column.id==='created_at')return dateTime(lead.created_at,{},language);
  return (lead.campaigns||[]).length?<span>{lead.campaigns.map((c,i)=><Link key={c.campaign_id} to={'/campaigns/'+c.campaign_id}>{i>0?', ':''}{c.campaign_name}</Link>)}</span>:'—';
 };
 return <div className={`sk-contact-layout ${drawer?'with-drawer':''}`} aria-busy={loading}>
  <div className="sk-contacts-content"><div className="sk-breadcrumb"><Link to="/leads">{t('contacts.contacts')}</Link><Icon name="next" size={13}/><span>{list?lists.find(l=>String(l.id)===list)?.name:t('contacts.allContacts')}</span></div>
   <div className="sk-page-heading"><div><h1>{t('contacts.contacts')}</h1><p>{t('contacts.description')}</p></div><div className="sk-heading-actions"><div className="sk-heading-meta"><Icon name="contacts" size={24}/><div><strong className="sk-heading-count">{filtered.length.toLocaleString(language)}</strong><small className="sk-muted">{query||list||status||fieldFilter.key?t('contacts.matchingCount'):t('contacts.allCount')}</small></div></div><Button to="/analytics" icon="chart">{t('contacts.statistics')}</Button></div></div>
   <ErrorNotice error={error} onRetry={reload}/>
   <div className="sk-toolbar"><Button variant="primary" icon="plus" onClick={()=>openModal('contact')}>{t('contacts.add')}</Button><Button icon="upload" onClick={()=>fileRef.current?.click()}>{t('contacts.import')}</Button><Button icon="settings" onClick={()=>setDrawer(true)} aria-expanded={drawer}>{t('contacts.manageFields')}</Button>
    <div className="sk-popover-container" ref={columnRef}><Button icon="eye" onClick={()=>setColumnMenu(v=>!v)} aria-expanded={columnMenu}>{t('contacts.columns')}</Button>{columnMenu&&<div className="sk-popover"><h3>{t('contacts.columns')}</h3><div className="sk-scroll">{columns.map(c=><label key={c.id}><input type="checkbox" checked={c.id==='email'||!hidden.has(c.id)} disabled={c.id==='email'} onChange={()=>toggleColumn(c.id)}/><span>{c.label}</span></label>)}</div><Button variant="ghost" onClick={()=>{setHidden(new Set());try{localStorage.setItem(prefKey,'[]');}catch{}}}>{t('contacts.showAll')}</Button></div>}</div>
    <input type="file" accept=".csv,.xlsx,.xlsm" ref={fileRef} className="sk-hidden-file" onChange={e=>{if(e.target.files[0])setFile(e.target.files[0]);e.target.value='';}}/>
   </div>
   {params.get('import')&&<p className="sk-small sk-muted sk-inline-hint">{t('contacts.importHint')}</p>}
   <div className="sk-filters"><select aria-label={t('contacts.archiveScope')} value={scope} onChange={e=>setScope(e.target.value)}>{['current','archived','all'].map(value=><option key={value} value={value}>{t('contacts.scope.'+value)}</option>)}</select><div className="sk-search-input"><Icon name="search" size={19}/><input aria-label={t('contacts.search')} placeholder={t('contacts.searchPlaceholder')} value={search} onChange={e=>setSearch(e.target.value)}/></div><select aria-label={t('contacts.statusesLabel')} value={status} onChange={e=>setStatus(e.target.value)}><option value="">{t('contacts.statusAll')}</option><option value="active">{t('contacts.statuses.active')}</option><option value="replied">{t('contacts.statuses.replied')}</option><option value="bounced">{t('contacts.statuses.bounced')}</option><option value="unsubscribed">{t('contacts.statuses.unsubscribed')}</option></select><select aria-label={t('contacts.list')} value={list} onChange={e=>setList(e.target.value)}><option value="">{t('contacts.segmentAll')}</option>{lists.map(l=><option key={l.id} value={l.id}>{l.name} ({l.member_count})</option>)}</select><Button icon="filter" className="compact" onClick={()=>{setFilterDraft({...fieldFilter});openModal('filters');}}>{t('contacts.moreFilters')}</Button></div>
   {fieldFilter.key&&<div className="sk-toolbar sk-filter-chip-row"><Badge tone="blue">{fieldFilterLabel}: {fieldFilter.value}</Badge><Button variant="ghost" onClick={()=>setFieldFilter({key:'',value:''})}>{t('contacts.clearFilter')}</Button></div>}
   <div className="sk-table-wrap sk-contacts-table"><table className="sk-table"><thead><tr><th><input type="checkbox" aria-label={t('contacts.selectPage')} checked={rows.length>0&&rows.every(l=>selected.has(l.id))} disabled={loading||!!error} onChange={selectPage}/></th>{visible.map(c=><th key={c.id}>{c.label}</th>)}<th aria-label={t('contacts.actions')}/></tr></thead><tbody>{rows.map(l=><tr key={l.id} className={selected.has(l.id)?'is-selected':''}><td><input type="checkbox" aria-label={t('contacts.selectContact',{email:l.email})} checked={selected.has(l.id)} disabled={loading||!!error} onChange={()=>toggle(l.id)}/></td>{visible.map(c=><td key={c.id}>{renderCell(l,c)}</td>)}<td><Link to={'/leads/'+l.id} className="sk-icon-button" aria-label={t('contacts.openContact',{email:l.email})}><Icon name="more" size={18}/></Link></td></tr>)}</tbody></table>{!rows.length&&!error&&<Empty icon="contacts">{loading?t('contacts.loadingContacts'):t('contacts.noMatches')}</Empty>}</div>
   <div className="sk-table-footer"><div className="sk-toolbar"><span>{t('contacts.selected',{count:selected.size})}</span><Button className="compact" disabled={!selected.size||busy||loading||!!error||leads.some(l=>selected.has(l.id)&&l.archived_at)} onClick={openCampaigns}>{t('contacts.enroll')}</Button><Button className="compact" disabled={!selected.size||busy||loading||!!error} onClick={()=>archive(scope!=='archived')}>{t(scope==='archived'?'contacts.restore':'contacts.archive')}</Button><Button className="compact" variant="danger" icon="delete" disabled={!selected.size||busy||loading||!!error} onClick={remove}>{t('contacts.delete')}</Button><Button className="compact" icon="download" onClick={exportContacts} disabled={!!fieldFilter.key} title={fieldFilter.key?t('contacts.exportHint'):undefined}>{t('contacts.export')}</Button></div><div className="sk-pagination"><button aria-label={t('contacts.previous')} disabled={current===1} onClick={()=>setPage(p=>p-1)}><Icon name="prev" size={17}/></button>{Array.from({length:Math.min(5,pages)},(_,i)=>Math.min(Math.max(1,current-2),Math.max(1,pages-4))+i).map(p=><button className={p===current?'active':''} key={p} aria-current={p===current?'page':undefined} onClick={()=>setPage(p)}>{p}</button>)}{pages>5&&<span> / {pages}</span>}<button aria-label={t('contacts.next')} disabled={current===pages} onClick={()=>setPage(p=>p+1)}><Icon name="next" size={17}/></button></div></div>
   <div className="sk-toolbar sk-contact-tools-row"><Button variant="ghost" icon="block" onClick={openSuppression}>{t('contacts.suppression')}</Button><Link className="sk-small sk-muted" to="/contacts-tools">{t('contacts.tools')}</Link></div>
  </div>
  {drawer&&<FieldManager fields={fields} onRefresh={async()=>{await refreshFields();await reload();}} onClose={()=>setDrawer(false)}/>}
  {file&&<ContactImport file={file} onClose={()=>setFile(null)} onDone={reload}/>}
  {modal==='contact'&&<Modal title={t('contacts.add')} onClose={()=>setModal(null)} busy={busy}><ErrorNotice error={formError}/><form onSubmit={create}><div className="sk-form"><label>{t('contacts.email')}<input required type="email" autoComplete="off" value={newContact.email} onChange={e=>setNewContact(p=>({...p,email:e.target.value}))}/></label><label>{t('contacts.name')}<input value={newContact.name} maxLength={255} onChange={e=>setNewContact(p=>({...p,name:e.target.value}))}/></label>{fields.filter(f=>!f.system).map(f=><label key={f.key}>{f.label}<FieldInput field={f} value={newContact.custom_data[f.key]} onChange={v=>setNewContact(p=>({...p,custom_data:{...p.custom_data,[f.key]:v}}))}/></label>)}</div><p className="sk-small sk-muted sk-form-note">{t('contacts.createSafety')}</p><div className="sk-form-actions"><Button onClick={()=>setModal(null)} disabled={busy}>{t('contacts.cancel')}</Button><Button type="submit" variant="primary" disabled={busy}>{busy?t('contacts.saving'):t('contacts.create')}</Button></div></form></Modal>}
  {modal==='campaign'&&<Modal title={t('contacts.enrollTitle')} onClose={()=>setModal(null)} small busy={busy}><ErrorNotice error={formError}/><p className="sk-small sk-muted">{t('contacts.enrollSafety',{count:selected.size})}</p><label className="sk-form sk-form-single">{t('contacts.campaign')}<select value={campaignId} onChange={e=>setCampaignId(e.target.value)}><option value="">{t('contacts.chooseCampaign')}</option>{campaigns.map(c=><option key={c.id} value={c.id}>{c.name} · {c.paused?t('contacts.campaignPaused'):t('contacts.campaignActive')}</option>)}</select></label><div className="sk-form-actions"><Button onClick={()=>setModal(null)}>{t('contacts.cancel')}</Button><Button variant="primary" disabled={!campaignId||busy} onClick={enroll}>{t('contacts.enroll')}</Button></div></Modal>}
  {modal==='filters'&&<Modal title={t('contacts.filterTitle')} onClose={()=>setModal(null)} small><div className="sk-form sk-form-single"><label>{t('contacts.field')}<select value={filterDraft.key} onChange={e=>setFilterDraft(p=>({...p,key:e.target.value}))}><option value="">{t('contacts.noFilter')}</option>{fields.filter(f=>!f.system).map(f=><option key={f.key} value={f.key}>{f.label}</option>)}</select></label><label>{t('contacts.contains')}<input value={filterDraft.value} onChange={e=>setFilterDraft(p=>({...p,value:e.target.value}))}/></label></div><div className="sk-form-actions"><Button variant="primary" onClick={()=>{setFieldFilter({...filterDraft});setModal(null);}}>{t('contacts.apply')}</Button></div></Modal>}
  {modal==='suppression'&&<Modal title={t('contacts.suppressionTitle')} onClose={()=>setModal(null)} busy={busy}><ErrorNotice error={formError}/><p className="sk-small sk-muted">{t('contacts.suppressionHelp')}</p><form onSubmit={addBlock} className="sk-toolbar sk-suppression-form"><input required type="email" aria-label={t('contacts.blockAddress')} placeholder={t('contacts.emailAddress')} value={blockEmail} onChange={e=>setBlockEmail(e.target.value)}/><Button type="submit" icon="plus" disabled={busy}>{t('contacts.addAddress')}</Button></form><div className="sk-table-wrap"><table className="sk-table"><thead><tr><th>{t('contacts.email')}</th><th>{t('contacts.reason')}</th><th>{t('contacts.added')}</th><th/></tr></thead><tbody>{suppression.map(x=><tr key={x.id}><td>{x.email}</td><td>{x.reason==='unsubscribe'?t('contacts.unsubscribe'):x.reason==='manual'?t('contacts.manual'):x.reason}</td><td>{dateTime(x.created_at,{},language)}</td><td><Button className="compact" disabled={busy} onClick={()=>removeBlock(x)}>{t('contacts.removeBlock')}</Button></td></tr>)}</tbody></table>{!suppression.length&&<Empty icon="block">{t('contacts.noSuppression')}</Empty>}</div></Modal>}
 </div>;
}
