import {useEffect, useState} from 'react';
import {api, postJsonForDownload} from '../api';
import {useLanguage} from '../context/LanguageContext';
import {Button} from './ui/Button';

const copy={
 pl:['Zdalne kopie zapasowe','Opcjonalny cel zdalny','Zapisz cel','Test połączenia','Odśwież listę kopii','Wczytaj do przywracania','Historia transferów','Włącz zdalny backup','Katalog / prefiks','Liczba zachowanych kopii','Host','Port','Użytkownik','Hasło','Odcisk klucza SSH (SHA256)','Endpoint HTTPS (opcjonalny)','Region','Bucket','Access key','Secret key','Zapisano.','Test zapisu, odczytu i usuwania zakończony poprawnie.','Wczytywanie…','Zapisz zmiany przed testem lub odczytem.','Brak kopii do wyświetlenia.','Transfery zewnętrzne są wyłączone w demo.','Pozostaw puste, aby zachować zapisany sekret.','Kopie są szyfrowane przed wysyłką. Harmonogram i hasło ustawiasz powyżej. Pobranie kopii nie uruchamia odtwarzania.','Błąd operacji.','Oczekuje','Zweryfikowano','Błąd','Data','Plik','Stan'],
 en:['Remote backups','Optional remote destination','Save destination','Test connection','Refresh backup list','Load for restore','Transfer history','Enable remote backup','Directory / prefix','Backups to retain','Host','Port','Username','Password','SSH key fingerprint (SHA256)','HTTPS endpoint (optional)','Region','Bucket','Access key','Secret key','Saved.','Write, read and delete test passed.','Loading…','Save changes before testing or reading.','No backups to display.','External transfers are disabled in demo.','Leave blank to keep the saved secret.','Backups are encrypted before transfer. Configure the schedule and password above. Downloading does not start a restore.','Operation failed.','Pending','Verified','Failed','Date','File','Status'],
 de:['Remote-Backups','Optionales Remote-Ziel','Ziel speichern','Verbindung testen','Backup-Liste aktualisieren','Zur Wiederherstellung laden','Übertragungsverlauf','Remote-Backup aktivieren','Verzeichnis / Präfix','Aufbewahrte Backups','Host','Port','Benutzername','Passwort','SSH-Fingerabdruck (SHA256)','HTTPS-Endpunkt (optional)','Region','Bucket','Zugriffsschlüssel','Geheimer Schlüssel','Gespeichert.','Schreib-, Lese- und Löschtest bestanden.','Wird geladen…','Änderungen vor dem Test oder Lesen speichern.','Keine Backups vorhanden.','Externe Übertragungen sind in der Demo deaktiviert.','Leer lassen, um das gespeicherte Geheimnis beizubehalten.','Backups werden vor der Übertragung verschlüsselt. Zeitplan und Passwort oben einstellen. Das Herunterladen startet keine Wiederherstellung.','Vorgang fehlgeschlagen.','Ausstehend','Verifiziert','Fehlgeschlagen','Datum','Datei','Status'],
 ru:['Удалённые резервные копии','Необязательное удалённое хранилище','Сохранить хранилище','Проверить подключение','Обновить список копий','Загрузить для восстановления','История передач','Включить удалённое копирование','Каталог / префикс','Количество хранимых копий','Хост','Порт','Имя пользователя','Пароль','Отпечаток ключа SSH (SHA256)','HTTPS endpoint (необязательно)','Регион','Bucket','Ключ доступа','Секретный ключ','Сохранено.','Проверка записи, чтения и удаления пройдена.','Загрузка…','Сохраните изменения перед проверкой или чтением.','Нет резервных копий.','Внешние передачи отключены в демо.','Оставьте пустым, чтобы сохранить текущий секрет.','Копии шифруются перед отправкой. Расписание и пароль настраиваются выше. Загрузка не запускает восстановление.','Ошибка операции.','Ожидает','Проверено','Ошибка','Дата','Файл','Статус']
};
export default function RemoteBackups({onRestoreFile}) {
 const {language}=useLanguage(); const t=copy[language]||copy.en;
 const [target,setTarget]=useState(null),[draft,setDraft]=useState({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[files,setFiles]=useState([]),[history,setHistory]=useState([]);
 const dirty=target && JSON.stringify(draft)!==JSON.stringify(target.config);
 const load=async()=>{const r=await api.get('/settings/backup/remote');if(!r?.config)throw new Error('Invalid remote configuration response');setTarget(r);setDraft(r.config);const h=await api.get('/settings/backup/remote/history');setHistory(h.items||[]);};
 useEffect(()=>{load().catch(()=>setError(t[28]));},[]);
 const act=async(fn)=>{if(busy)return;setBusy(true);setError('');setMessage('');try{await fn();}catch{setError(t[28]);}finally{setBusy(false);}};
 const field=(key,label,type='text')=><label className="flex flex-col gap-1 min-w-0 text-sm" key={key}>{t[label]}<input type={type} aria-label={t[label]} autoComplete={type==='password'?'new-password':'off'} className="w-full min-w-0 rounded border border-gray-300 dark:border-gray-600 bg-transparent p-2" value={draft[key]??''} onChange={e=>setDraft({...draft,[key]:type==='number'?Number(e.target.value):e.target.value})} placeholder={target?.secrets?.[key]?t[26]:''}/></label>;
 return <section className="border-t border-gray-200 dark:border-gray-700 pt-4 mt-4 space-y-3" aria-label={t[0]}>
 <h3 className="font-semibold">{t[0]}</h3><p className="text-sm text-gray-600 dark:text-gray-400">{t[27]}</p>
 {error&&<p role="alert" className="text-sm text-red-600 dark:text-red-400">{error}</p>}{message&&<p role="status" className="text-sm text-emerald-700 dark:text-emerald-400">{message}</p>}
 {!target?<Button variant="outline" onClick={()=>act(load)} disabled={busy}>{t[22]}</Button>:<>
 {target.demo&&<p className="text-sm text-amber-700 dark:text-amber-400">{t[25]}</p>}
 <fieldset disabled={busy} className="space-y-3"><legend className="sr-only">{t[1]}</legend>
 <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={!!draft.enabled} onChange={e=>setDraft({...draft,enabled:e.target.checked})}/>{t[7]}</label>
 <label className="flex flex-col gap-1 text-sm">{t[1]}<select value={draft.kind||'s3'} onChange={e=>setDraft({kind:e.target.value,enabled:false,prefix:'sekaro',retention:14})} className="rounded border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-900 p-2"><option value="s3">S3</option><option value="sftp">SFTP</option><option value="ftps">FTPS (TLS)</option></select></label>
 <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
 {draft.kind==='s3'?<>{field('endpoint',15)}{field('region',16)}{field('bucket',17)}{field('access_key',18,'password')}{field('secret_key',19,'password')}</>:<>{field('host',10)}{field('port',11,'number')}{field('username',12)}{field('password',13,'password')}{draft.kind==='sftp'&&field('fingerprint',14)}</>}
 {field('prefix',8)}{field('retention',9,'number')}
 </div><div className="flex flex-wrap gap-2">
 <Button size="sm" disabled={!dirty||!target.encryption_available||target.demo} onClick={()=>act(async()=>{const r=await api.put('/settings/backup/remote',{revision:target.revision,config:draft});setTarget(r);setDraft(r.config);setFiles([]);setMessage(t[20]);})}>{t[2]}</Button>
 <Button size="sm" variant="outline" disabled={dirty||!target.revision||target.demo} onClick={()=>act(async()=>{await api.post('/settings/backup/remote/test',{});setMessage(t[21]);})}>{t[3]}</Button>
 <Button size="sm" variant="outline" disabled={dirty||!target.revision||target.demo} onClick={()=>act(async()=>{const r=await api.get('/settings/backup/remote/files');setFiles(r.files);const h=await api.get('/settings/backup/remote/history');setHistory(h.items||[]);})}>{t[4]}</Button>
 </div></fieldset>{dirty&&<p className="text-xs" role="status">{t[23]}</p>}
 <div className="space-y-2">{!files.length?<p className="text-sm text-gray-500">{t[24]}</p>:files.map(name=><div key={name} className="flex flex-wrap items-center justify-between gap-2 border rounded p-2"><span className="text-xs break-all">{name}</span><Button size="sm" variant="outline" disabled={busy||dirty} onClick={()=>act(async()=>{const response=await postJsonForDownload('/settings/backup/remote/download',{name});const blob=await response.blob();onRestoreFile(new File([blob],name,{type:'application/octet-stream'}));})}>{t[5]}</Button></div>)}</div>
 <h4 className="text-sm font-medium">{t[6]}</h4><div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr>{[32,33,34].map(i=><th key={i} className="p-2 text-left">{t[i]}</th>)}</tr></thead><tbody>{history.map(h=><tr key={h.id}><td className="p-2">{h.created_at}</td><td className="p-2 break-all">{h.filename}</td><td className="p-2">{t[{pending:29,verified:30,failed:31}[h.status]]||h.status}</td></tr>)}</tbody></table></div>
 </>}
 </section>;
}
