import {useEffect,useRef,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {api} from '../api';
import {Button,Panel,PageFrame,Empty,ErrorNotice,Badge} from './ui';
import Modal from './Modal';
import {useCrmText} from './crm-text';
import './crm.css';

export function AddToGroup({leadIds,onClose,onSaved}){
 const t=useCrmText(),[groups,setGroups]=useState([]),[id,setId]=useState('new'),[name,setName]=useState(''),[error,setError]=useState(null),[busy,setBusy]=useState(false),lock=useRef(false);
 useEffect(()=>{let live=true;api.get('/leads/lists').then(r=>{if(live)setGroups(r);}).catch(e=>{if(live)setError(e);});return()=>{live=false;};},[]);
 const save=async e=>{e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError(null);try{let groupId=id;if(id==='new'){const r=await api.post('/leads/lists',{name:name.trim(),lead_ids:leadIds});groupId=r.id;}else await api.post(`/leads/lists/${id}/members`,{lead_ids:leadIds});onSaved(groupId);}catch(e){setError(e);}finally{lock.current=false;setBusy(false);}};
 return <Modal title={t('addToGroup')} onClose={onClose} busy={busy} small><ErrorNotice error={error}/><form onSubmit={save}><div className="sk-form"><label>{t('choose')}<select value={id} onChange={e=>setId(e.target.value)}><option value="new">{t('new')}</option>{groups.map(g=><option key={g.id} value={g.id}>{g.name} ({g.member_count})</option>)}</select></label>{id==='new'&&<label>{t('name')}<input required maxLength={255} value={name} onChange={e=>setName(e.target.value)}/></label>}</div><p>{t('selected')}: {leadIds.length}</p><div className="sk-form-actions"><Button onClick={onClose} disabled={busy}>{t('cancel')}</Button><Button type="submit" variant="primary" disabled={busy||(id==='new'&&!name.trim())||(!leadIds.length&&id!=='new')}>{t(id==='new'?'create':'save')}</Button></div></form></Modal>;
}
function MemberPicker({groupId,onClose,onSaved}){
 const t=useCrmText(),[q,setQ]=useState(''),[contacts,setContacts]=useState([]),[selected,setSelected]=useState([]),[error,setError]=useState(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),lock=useRef(false);
 useEffect(()=>{let live=true;setLoading(true);const timer=setTimeout(()=>api.get('/leads?q='+encodeURIComponent(q)).then(r=>{if(live){setContacts(r);setError(null);}}).catch(e=>{if(live)setError(e);}).finally(()=>{if(live)setLoading(false);}),200);return()=>{live=false;clearTimeout(timer);};},[q]);
 const save=async()=>{if(lock.current)return;lock.current=true;setBusy(true);setError(null);try{await api.post(`/leads/lists/${groupId}/members`,{lead_ids:selected});onSaved();}catch(e){setError(e);}finally{lock.current=false;setBusy(false);}};
 return <Modal title={t('addMembers')} onClose={onClose} busy={busy}><ErrorNotice error={error}/><input type="search" aria-label={t('search')} placeholder={t('search')} value={q} onChange={e=>setQ(e.target.value)}/><div className="sk-group-picker">{loading?<p role="status">{t('loading')}</p>:contacts.length?contacts.map(c=><label key={c.id}><input type="checkbox" checked={selected.includes(c.id)} onChange={e=>setSelected(s=>e.target.checked?[...s,c.id]:s.filter(id=>id!==c.id))}/><span>{c.name||c.email}<small>{c.email}</small></span></label>):<Empty>{t('empty')}</Empty>}</div><div className="sk-form-actions"><span>{t('selected')}: {selected.length}</span><Button onClick={save} variant="primary" disabled={busy||!selected.length}>{t('addMembers')}</Button></div></Modal>;
}
export default function ContactGroups(){
 const t=useCrmText(),[params,setParams]=useSearchParams(),id=params.get('group'),[groups,setGroups]=useState([]),[members,setMembers]=useState([]),[selected,setSelected]=useState([]),[modal,setModal]=useState(null),[q,setQ]=useState(''),[error,setError]=useState(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[reload,setReload]=useState(0),lock=useRef(false);
 useEffect(()=>{let live=true;api.get('/leads/lists').then(r=>{if(live)setGroups(r);}).catch(e=>{if(live)setError(e);});return()=>{live=false;};},[reload]);
 useEffect(()=>{let live=true;setSelected([]);setMembers([]);setLoading(true);setError(null);if(!id){setLoading(false);return;}api.get('/leads?scope=all&list_id='+encodeURIComponent(id)).then(r=>{if(live)setMembers(r);}).catch(e=>{if(live)setError(e);}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[id,reload]);
 const refresh=()=>{setModal(null);setReload(n=>n+1);};
 const remove=async()=>{if(lock.current)return;lock.current=true;setBusy(true);setError(null);try{await api.post(`/leads/lists/${id}/members/remove`,{lead_ids:selected});refresh();}catch(e){setError(e);}finally{lock.current=false;setBusy(false);}};
 const group=groups.find(g=>String(g.id)===id),visible=members.filter(c=>(c.name+' '+c.email).toLowerCase().includes(q.toLowerCase()));
 return <PageFrame title={t('groups')} description={t('help')} actions={<Button icon="plus" variant="primary" onClick={()=>setModal('new')}>{t('newGroup')}</Button>}><ErrorNotice error={error}/><div className="sk-group-layout"><Panel title={t('groups')} icon="contacts"><div className="sk-group-list">{groups.map(g=><Link key={g.id} to={'/crm/groups?group='+g.id} aria-current={String(g.id)===id?'page':undefined}>{g.name}<Badge>{g.member_count}</Badge></Link>)}{!groups.length&&<p>{t('choose')}</p>}</div></Panel><Panel title={group?.name||t('choose')}><div className="sk-group-content">{group?<><div className="sk-toolbar"><Button icon="plus" onClick={()=>setModal('members')}>{t('addMembers')}</Button><Button disabled={!selected.length||busy||loading} onClick={remove}>{t('removeMembers')} ({selected.length})</Button><input type="search" aria-label={t('search')} placeholder={t('search')} value={q} onChange={e=>setQ(e.target.value)}/></div><p className="sk-muted">{t('membershipHelp')}</p>{loading?<p role="status">{t('loading')}</p>:<div className="sk-table-wrap"><table className="sk-table"><thead><tr><th>{t('selected')}</th><th>{t('contacts')}</th><th>E-mail</th></tr></thead><tbody>{visible.map(c=><tr key={c.id}><td><input type="checkbox" aria-label={c.email} checked={selected.includes(c.id)} onChange={e=>setSelected(s=>e.target.checked?[...s,c.id]:s.filter(x=>x!==c.id))}/></td><td><Link to={'/leads/'+c.id}>{c.name||c.email}</Link></td><td>{c.email}</td></tr>)}</tbody></table>{!visible.length&&<Empty>{t('empty')}</Empty>}</div>}</>:<Empty icon="contacts">{t('choose')}</Empty>}</div></Panel></div>{modal==='new'&&<AddToGroup leadIds={[]} onClose={()=>setModal(null)} onSaved={newId=>{setParams({group:String(newId)});refresh();}}/>}{modal==='members'&&<MemberPicker groupId={id} onClose={()=>setModal(null)} onSaved={refresh}/>}</PageFrame>;
}
export function CampaignGroupPicker({campaignId,onAdded}){
 const t=useCrmText(),[open,setOpen]=useState(false),[groups,setGroups]=useState([]),[id,setId]=useState(''),[skip,setSkip]=useState(true),[error,setError]=useState(null),[busy,setBusy]=useState(false),[result,setResult]=useState(null),lock=useRef(false);
 useEffect(()=>{if(!open)return;let live=true;api.get('/leads/lists').then(r=>{if(live)setGroups(r);}).catch(e=>{if(live)setError(e);});return()=>{live=false;};},[open]);
 const enroll=async e=>{e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError(null);try{const r=await api.post(`/campaigns/${campaignId}/contact-groups/${id}?skip_duplicates=${skip}`,{});setResult(r);setOpen(false);onAdded();}catch(e){setError(e);}finally{lock.current=false;setBusy(false);}};
 return <><Button size="sm" onClick={()=>{setError(null);setId('');setOpen(true);}}>{t('fromGroup')}</Button>{result&&<div className="sk-group-result" role="status">{t('added')}: {result.added} · {t('duplicates')}: {result.already_enrolled} · {t('suppressed')}: {result.suppressed} · {t('errors')}: {result.errors}</div>}{open&&<Modal title={t('fromGroup')} onClose={()=>setOpen(false)} busy={busy} small><ErrorNotice error={error}/><form onSubmit={enroll}><div className="sk-form"><label>{t('choose')}<select required value={id} onChange={e=>setId(e.target.value)}><option value="">{t('choose')}</option>{groups.map(g=><option key={g.id} value={g.id} disabled={!g.member_count}>{g.name} ({g.member_count})</option>)}</select></label><label><input type="checkbox" checked={skip} onChange={e=>setSkip(e.target.checked)}/>{t('skip')}</label></div><p className="sk-form-note">{t('safety')}</p><div className="sk-form-actions"><Button onClick={()=>setOpen(false)} disabled={busy}>{t('cancel')}</Button><Button type="submit" variant="primary" disabled={busy||!id}>{t('enroll')}</Button></div></form></Modal>}</>;
}
