import {useUiLanguage} from '../context/LanguageContext';
const keys=['contacts','groups','companies','opportunities','activities','calendar','help','newGroup','name','create','save','cancel','search','selected','addMembers','removeMembers','members','empty','choose','new','addToGroup','fromGroup','enroll','safety','skip','added','duplicates','suppressed','errors','loading','membershipHelp'];
const rows={
 pl:['Kontakty','Grupy kontaktów','Firmy','Szanse','Zadania i spotkania','Kalendarz','Organizuj istniejące kontakty i wybieraj grupy odbiorców w kampaniach.','Nowa grupa','Nazwa grupy','Utwórz grupę','Zapisz','Anuluj','Szukaj kontaktów','Zaznaczono','Dodaj kontakty','Usuń z grupy','Członkowie','Brak kontaktów','Wybierz grupę','Utwórz nową grupę','Dodaj do grupy','Z grupy kontaktów','Dodaj odbiorców','Dodanie do aktywnej kampanii może uruchomić wysyłkę zgodnie z jej ustawieniami. Blokady i archiwizacja są respektowane.','Pomiń kontakty już przypisane do dowolnej kampanii','Dodano','Już przypisane','Zablokowane','Pominięte / błędy','Ładowanie…','Usunięcie z grupy zachowuje kontakt i jego przypisania do kampanii.'],
 en:['Contacts','Contact groups','Companies','Opportunities','Tasks and meetings','Calendar','Organize existing contacts and select recipient groups in campaigns.','New group','Group name','Create group','Save','Cancel','Search contacts','Selected','Add contacts','Remove from group','Members','No contacts','Select group','Create new group','Add to group','From contact group','Add recipients','Adding to an active campaign may start sending under its settings. Suppression and archiving are respected.','Skip contacts already enrolled in any campaign','Added','Already enrolled','Suppressed','Skipped / errors','Loading…','Removing a member keeps the contact and its campaign enrollments.'],
 de:['Kontakte','Kontaktgruppen','Unternehmen','Verkaufschancen','Aufgaben und Termine','Kalender','Vorhandene Kontakte organisieren und Empfängergruppen in Kampagnen auswählen.','Neue Gruppe','Gruppenname','Gruppe erstellen','Speichern','Abbrechen','Kontakte suchen','Ausgewählt','Kontakte hinzufügen','Aus Gruppe entfernen','Mitglieder','Keine Kontakte','Gruppe wählen','Neue Gruppe erstellen','Zur Gruppe hinzufügen','Aus Kontaktgruppe','Empfänger hinzufügen','Das Hinzufügen zu einer aktiven Kampagne kann den Versand starten. Sperren und Archivierung werden berücksichtigt.','Kontakte überspringen, die bereits einer Kampagne zugeordnet sind','Hinzugefügt','Bereits zugeordnet','Gesperrt','Übersprungen / Fehler','Laden…','Das Entfernen aus der Gruppe behält den Kontakt und seine Kampagnenzuordnungen.'],
 ru:['Контакты','Группы контактов','Компании','Сделки','Задачи и встречи','Календарь','Объединяйте существующие контакты и выбирайте группы получателей в кампаниях.','Новая группа','Название группы','Создать группу','Сохранить','Отмена','Поиск контактов','Выбрано','Добавить контакты','Удалить из группы','Участники','Нет контактов','Выберите группу','Создать новую группу','Добавить в группу','Из группы контактов','Добавить получателей','Добавление в активную кампанию может запустить отправку. Блокировки и архивирование учитываются.','Пропустить контакты, уже добавленные в любую кампанию','Добавлено','Уже добавлены','Заблокировано','Пропущено / ошибки','Загрузка…','Удаление из группы сохраняет контакт и его участие в кампаниях.']
};
export function useCrmText(){const {language}=useUiLanguage();return key=>(rows[language]||rows.en)[keys.indexOf(key)]||key;}
