import {useState,useRef} from 'react';
import {api} from '../api';
import {useConfirm} from '../context/ConfirmContext';
import {Button,Icon,Empty,ErrorNotice} from './ui';
export const fieldTypes={text:'Tekst',textarea:'Tekst (wiele linii)',number:'Liczba',date:'Data',select:'Lista (jednokrotny wybór)'};
export function FieldInput({field,value,onChange,...props}){if(field.field_type==='textarea')return <textarea {...props} value={value??''} onChange={e=>onChange(e.target.value)}/>;if(field.field_type==='select')return <select {...props} value={value??''} onChange={e=>onChange(e.target.value)}><option value="">Brak wartości</option>{value&&!(field.options||[]).includes(String(value))&&<option value={value}>{value} (wcześniejsza wartość)</option>}{(field.options||[]).map(v=><option key={v}>{v}</option>)}</select>;return <input {...props} type={['date','number'].includes(field.field_type)?field.field_type:'text'} step={field.field_type==='number'?'any':undefined} value={typeof value==='object'?JSON.stringify(value):value??''} onChange={e=>onChange(e.target.value)}/>;}
export default function FieldManager({fields,onRefresh,onClose}){
 const [form,setForm]=useState({label:'',key:'',field_type:'text',options:''}),[editing,setEditing]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[customKey,setCustomKey]=useState(false);const labelRef=useRef(null),confirm=useConfirm();
 const slug=v=>v.toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replaceAll('ł','l').replace(/[^\p{L}\p{N}_]+/gu,'_').replace(/^_+|_+$/g,'').slice(0,64);
 const reset=()=>{setEditing(null);setForm({label:'',key:'',field_type:'text',options:''});setCustomKey(false);setError('');labelRef.current?.focus();};
 const submit=async e=>{e.preventDefault();setBusy(true);setError('');const payload={key:form.key,label:form.label,field_type:form.field_type,options:form.options.split('\n').map(s=>s.trim()).filter(Boolean)};try{if(editing?.id)await api.patch('/contact-fields/'+editing.id,payload);else await api.post('/contact-fields',payload);await onRefresh();reset();}catch(e){setError(e);}finally{setBusy(false);}};
 const edit=f=>{setEditing(f);setCustomKey(true);setForm({label:f.label,key:f.key,field_type:f.field_type||'text',options:(f.options||[]).join('\n')});setTimeout(()=>labelRef.current?.focus(),0);};
 const remove=async f=>{if(!await confirm(`Usunąć pole „${f.label}” oraz WSZYSTKIE jego wartości z kontaktów? Tej operacji nie można cofnąć. Zmienne w istniejących szablonach pozostaną i mogą blokować start kampanii.`))return;setBusy(true);try{let id=f.id;if(!id){const created=await api.post('/contact-fields',{key:f.key,label:f.label});id=created.id;}await api.del('/contact-fields/'+id+'?purge=true');await onRefresh();if(editing?.key===f.key)reset();}catch(e){setError(e);}finally{setBusy(false);}};
 return <aside className="sk-drawer" aria-label="Zarządzanie własnymi polami"><div className="sk-drawer-head"><h2>Własne pola</h2><button className="sk-icon-button" aria-label="Zamknij własne pola" onClick={onClose}><Icon name="close"/></button></div><p className="sk-drawer-desc">Twórz i zarządzaj niestandardowymi polami kontaktów. Będą widoczne jako kolumny w tabeli.</p><Button icon="plus" variant="primary" className="sk-full-width" onClick={reset} disabled={busy}>Dodaj pole</Button><div className="sk-field-list">{fields.filter(f=>!f.system).map(f=><div className="sk-field-row" key={f.key}><Icon name={f.field_type==='select'?'tag':f.field_type==='date'?'calendar':f.field_type==='number'?'number':'template'} size={20}/><div><strong>{f.label||f.key}</strong><small>Typ: {fieldTypes[f.field_type]||'Tekst'}</small></div><button className="sk-icon-button" aria-label={`Edytuj pole ${f.label}`} title="Edytuj" onClick={()=>edit(f)} disabled={busy}><Icon name="edit" size={14}/></button><button className="sk-icon-button" aria-label={`Usuń pole ${f.label}`} title="Usuń pole z wartościami" onClick={()=>remove(f)} disabled={busy}><Icon name="delete" size={14}/></button></div>)}</div><ErrorNotice error={error}/><form className="sk-field-form" onSubmit={submit}><h3>{editing?'Edytuj pole':'Dodaj nowe pole'}</h3><label htmlFor="field-label">Nazwa pola</label><input id="field-label" ref={labelRef} value={form.label} required maxLength={255} placeholder="Nazwa Twojego pola" onChange={e=>setForm(p=>({...p,label:e.target.value,...(!customKey&&!editing?{key:slug(e.target.value)}:{})}))}/><div className="sk-small sk-muted" style={{marginTop:7}}><code>{'{{'+(form.key||'klucz_pola')+'}}'}</code>{!editing&&<button type="button" className="sk-btn sk-btn-ghost" onClick={()=>setCustomKey(v=>!v)}>Zmień klucz</button>}</div>{customKey&&!editing&&<><label htmlFor="field-key">Klucz zmiennej</label><input id="field-key" required value={form.key} maxLength={64} onChange={e=>setForm(p=>({...p,key:e.target.value}))}/></>}<label htmlFor="field-type">Typ pola</label><select id="field-type" value={form.field_type} onChange={e=>setForm(p=>({...p,field_type:e.target.value}))}>{Object.entries(fieldTypes).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>{form.field_type==='select'&&<><label htmlFor="field-options">Opcje (jedna na linię)</label><textarea id="field-options" rows={5} required placeholder={'Pierwsza opcja\nDruga opcja'} value={form.options} onChange={e=>setForm(p=>({...p,options:e.target.value}))}/></>}<div className="sk-form-actions"><Button onClick={reset}>Anuluj</Button><Button type="submit" variant="primary" disabled={busy||!form.key.trim()}>{busy?'Zapisywanie…':editing?'Zapisz pole':'Utwórz pole'}</Button></div></form></aside>;
}
