import {useState,useEffect,useRef} from 'react';
import {api} from '../api';
import {Button,Panel,ErrorNotice,Badge,dateTime} from '../redesign/ui';
import Modal from '../redesign/Modal';
import {useConfirm} from '../context/ConfirmContext';
import {useUiLanguage} from '../context/LanguageContext';
import './access.css';
const labels={pl:{title:'Użytkownicy i uprawnienia',users:'Użytkownicy',roles:'Role',teams:'Zespoły',audit:'Historia dostępu',add:'Dodaj',edit:'Edytuj',save:'Zapisz',cancel:'Anuluj',name:'Nazwa',username:'Login',email:'E-mail',password:'Hasło początkowe',role:'Rola bezpośrednia',teamRole:'Rola zespołu',none:'Brak',admin:'Administrator',active:'Aktywny',permissions:'Uprawnienia',members:'Członkowie',read:'Odczyt',write:'Zmiany',crm:'CRM',outreach:'Kampanie i harmonogram',mail:'Poczta',reports:'Raporty',templates:'Szablony',automation:'Automatyzacje',legacy:'Dotychczasowy dostęp do modułów',revoke:'Unieważnij sesje i klucze',confirm:'Zapisać zmianę dostępu? Uprawnienia dotyczą wszystkich danych w wybranych modułach tej instalacji.',revokeConfirm:'Unieważnić wszystkie sesje i klucze API tego użytkownika?',scope:'Role dotyczą całej instalacji. Dostęp wynika z sumy roli bezpośredniej i ról zespołów. Zespoły nie oddzielają danych. Administrator ma pełny dostęp, również do konfiguracji.',empty:'Brak wpisów',reload:'Odśwież',more:'Starsze wpisy',discard:'Odrzucić niezapisane zmiany?',effective:'Efektywny dostęp',noAccess:'Brak dostępu do modułów',readOnly:'Dostęp tylko do odczytu. Zmiany wymagają dodatkowych uprawnień.',denied:'Nie masz dostępu do tego modułu.',close:'Zamknij'},en:{title:'Users and permissions',users:'Users',roles:'Roles',teams:'Teams',audit:'Access history',add:'Add',edit:'Edit',save:'Save',cancel:'Cancel',name:'Name',username:'Username',email:'Email',password:'Initial password',role:'Direct role',teamRole:'Team role',none:'None',admin:'Administrator',active:'Active',permissions:'Permissions',members:'Members',read:'Read',write:'Write',crm:'CRM',outreach:'Campaigns and schedule',mail:'Mail',reports:'Reports',templates:'Templates',automation:'Automations',legacy:'Existing module access',revoke:'Revoke sessions and keys',confirm:'Save access changes? Permissions apply to all data in the selected modules of this installation.',revokeConfirm:'Revoke all sessions and API keys for this user?',scope:'Permissions are installation-wide and combine direct and team roles. Teams do not isolate data. Administrators have full access including configuration.',empty:'No entries',reload:'Refresh',more:'Older entries',discard:'Discard unsaved changes?',effective:'Effective access',noAccess:'No module access',readOnly:'Read-only access. Changes require additional permissions.',denied:'You do not have access to this module.',close:'Close'}};
labels.de={...labels.en,title:'Benutzer und Berechtigungen',users:'Benutzer',roles:'Rollen',teams:'Teams',audit:'Zugriffsverlauf',add:'Hinzufügen',edit:'Bearbeiten',save:'Speichern',cancel:'Abbrechen',name:'Name',username:'Benutzername',password:'Anfangspasswort',role:'Direkte Rolle',teamRole:'Teamrolle',none:'Keine',admin:'Administrator',active:'Aktiv',permissions:'Berechtigungen',members:'Mitglieder',read:'Lesen',write:'Ändern',outreach:'Kampagnen und Zeitplan',mail:'Postfach',reports:'Berichte',templates:'Vorlagen',automation:'Automatisierungen',legacy:'Bisheriger Modulzugriff',revoke:'Sitzungen und Schlüssel widerrufen',confirm:'Zugriff ändern? Berechtigungen gelten für alle Daten der ausgewählten Module dieser Installation.',revokeConfirm:'Alle Sitzungen und API-Schlüssel dieses Benutzers widerrufen?',scope:'Rollen gelten installationsweit. Direkte und Teamrollen werden kombiniert. Teams trennen keine Daten. Administratoren haben vollständigen Zugriff einschließlich Konfiguration.',empty:'Keine Einträge',reload:'Aktualisieren',more:'Ältere Einträge',discard:'Ungespeicherte Änderungen verwerfen?',effective:'Effektiver Zugriff',noAccess:'Kein Modulzugriff',readOnly:'Nur Lesezugriff. Änderungen erfordern weitere Berechtigungen.',denied:'Kein Zugriff auf dieses Modul.',close:'Schließen'};
labels.ru={...labels.en,title:'Пользователи и права',users:'Пользователи',roles:'Роли',teams:'Команды',audit:'История доступа',add:'Добавить',edit:'Редактировать',save:'Сохранить',cancel:'Отмена',name:'Название',username:'Логин',password:'Начальный пароль',role:'Прямая роль',teamRole:'Роль команды',none:'Нет',admin:'Администратор',active:'Активен',permissions:'Права',members:'Участники',read:'Чтение',write:'Изменения',outreach:'Кампании и расписание',mail:'Почта',reports:'Отчёты',templates:'Шаблоны',automation:'Автоматизации',legacy:'Прежний доступ к модулям',revoke:'Отозвать сеансы и ключи',confirm:'Сохранить доступ? Права распространяются на все данные выбранных модулей этой установки.',revokeConfirm:'Отозвать все сеансы и ключи API пользователя?',scope:'Права действуют во всей установке и суммируются из прямой роли и ролей команд. Команды не разделяют данные. Администратор имеет полный доступ, включая настройки.',empty:'Нет записей',reload:'Обновить',more:'Предыдущие записи',discard:'Отменить несохранённые изменения?',effective:'Итоговый доступ',noAccess:'Нет доступа к модулям',readOnly:'Только чтение. Для изменений нужны дополнительные права.',denied:'У вас нет доступа к этому модулю.',close:'Закрыть'};
for(const [lang,extra] of Object.entries({pl:{before:'Przed zmianą',after:'Po zmianie',id:'ID',role_id:'ID roli',administrator:'Administrator',revision:'Wersja',legacy_access:'Dotychczasowy dostęp',logout:'Wyloguj'},en:{before:'Before',after:'After',id:'ID',role_id:'Role ID',administrator:'Administrator',revision:'Version',legacy_access:'Existing access',logout:'Log out'},de:{before:'Vorher',after:'Nachher',id:'ID',role_id:'Rollen-ID',administrator:'Administrator',revision:'Version',legacy_access:'Bisheriger Zugriff',logout:'Abmelden'},ru:{before:'До',after:'После',id:'ID',role_id:'ID роли',administrator:'Администратор',revision:'Версия',legacy_access:'Прежний доступ',logout:'Выйти'}}))Object.assign(labels[lang],extra);
const actions={pl:['Utworzono konto','Zmieniono konto','Unieważniono sesje i klucze','Utworzono rolę','Zmieniono rolę','Utworzono zespół','Zmieniono zespół'],en:['User created','User updated','Sessions and keys revoked','Role created','Role updated','Team created','Team updated'],de:['Benutzer erstellt','Benutzer geändert','Sitzungen und Schlüssel widerrufen','Rolle erstellt','Rolle geändert','Team erstellt','Team geändert'],ru:['Пользователь создан','Пользователь изменён','Сеансы и ключи отозваны','Роль создана','Роль изменена','Команда создана','Команда изменена']};
for(const lang of Object.keys(labels))['user.created','user.updated','user.sessions_revoked','role.created','role.updated','team.created','team.updated'].forEach((key,i)=>{labels[lang][key]=actions[lang][i];});
export function useAccessText(){const {language}=useUiLanguage();return key=>(labels[language]||labels.pl)[key]||key;}
export default function AccessManagement(){
 const t=useAccessText(),{language}=useUiLanguage(),confirm=useConfirm();
 const lock=useRef(false);
 const [data,setData]=useState(null),[audit,setAudit]=useState([]),[auditMore,setAuditMore]=useState(false),[error,setError]=useState(null),[editor,setEditor]=useState(null),[draft,setDraft]=useState({}),[baseline,setBaseline]=useState(''),[busy,setBusy]=useState(false);
 async function load(){try{const [d,a]=await Promise.all([api.get('/access'),api.get('/access/audit')]);setData(d);setAudit(a);setAuditMore(a.length===100);}catch(e){setError(e);}}
 useEffect(()=>{load();},[]);
 const update=(key,value)=>setDraft(d=>({...d,[key]:value}));
 const open=(type,row)=>{const d=type==='users'?(row?{role_id:row.role_id,administrator:row.administrator,active:row.active,revision:row.revision}:{username:'',email:'',password:'',role_id:null,administrator:false}):type==='roles'?{name:row?.name||'',permissions:row?.permissions||[],revision:row?.revision??null}:{name:row?.name||'',role_id:row?.role_id??null,members:row?.members||[],revision:row?.revision??null};setEditor({type,id:row?.id});setDraft(d);setBaseline(JSON.stringify(d));setError(null);};
 const dismiss=async()=>{if(!busy&&(baseline===JSON.stringify(draft)||await confirm({message:t('discard')})))setEditor(null);};
 async function save(e){e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);try{if(!await confirm({message:t('confirm')}))return;const path='/access/'+editor.type;await (editor.id?api.put(path+'/'+editor.id,draft):api.post(path,draft));setEditor(null);await load();}catch(e){setError(e);}finally{lock.current=false;setBusy(false);}}
 async function revoke(u){if(lock.current)return;lock.current=true;setBusy(true);try{if(await confirm({message:t('revokeConfirm'),danger:true})){await api.post('/access/users/'+u.id+'/revoke-sessions',{revision:u.revision});await load();}}catch(e){setError(e);}finally{lock.current=false;setBusy(false);}}
 const roleSelect=key=><label>{t(key)}<select value={draft.role_id??''} onChange={e=>update('role_id',e.target.value?Number(e.target.value):null)}><option value="">{t('none')}</option>{data.roles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>;
 const permissionText=p=>t(p.split('.')[0])+' · '+t(p.split('.')[1]);
 const detail=(value)=>value&&typeof value==='object'?<dl>{Object.entries(value).map(([k,v])=><div key={k}><dt>{t(k)}</dt><dd>{Array.isArray(v)?v.map(x=>typeof x==='string'&&x.includes('.')?permissionText(x):String(x)).join(', '):typeof v==='object'?detail(v):String(v??'—')}</dd></div>)}</dl>:String(value??'—');
 return <div className="sk-access"><p>{t('scope')}</p><ErrorNotice error={error}/><Button disabled={busy} onClick={load}>{t('reload')}</Button>{data&&<>{['users','roles','teams'].map(type=><Panel key={type} title={t(type)} action={<Button disabled={busy} onClick={()=>open(type)}>{t('add')}</Button>}><div className="sk-table-wrap"><table className="sk-table"><thead><tr><th>{t('name')}</th><th>{t('effective')}</th><th>{t('edit')}</th></tr></thead><tbody>{data[type].map(row=><tr key={row.id}><td>{row.username||row.name}{type==='users'&&<><small>{row.email}</small><Badge>{row.active?t('active'):t('none')}</Badge></>}</td><td>{type==='users'?(row.administrator?t('admin'):row.legacy_access?t('legacy'):row.permissions.map(permissionText).join(', ')||t('noAccess')):type==='roles'?row.permissions.map(permissionText).join(', ')||t('noAccess'):<>{data.roles.find(r=>r.id===row.role_id)?.name||t('none')} · {t('members')}: {row.members.length}</>}</td><td><Button disabled={busy} onClick={()=>open(type,row)}>{t('edit')}</Button>{type==='users'&&<Button disabled={busy} onClick={()=>revoke(row)}>{t('revoke')}</Button>}</td></tr>)}</tbody></table></div></Panel>)}
 <Panel title={t('audit')}>{audit.map(a=><details key={a.id}><summary>{a.actor_name} · {dateTime(a.at,{},language)} · {t(a.action)}</summary>{detail(a.detail)}</details>)}{audit.length===0&&<p>{t('empty')}</p>}{auditMore&&<Button onClick={async()=>{try{const next=await api.get('/access/audit?before='+audit.at(-1).id);setAudit(a=>[...a,...next]);setAuditMore(next.length===100);}catch(e){setError(e);}}}>{t('more')}</Button>}</Panel>
 </>}{editor&&<Modal title={t(editor.type)} onClose={dismiss} busy={busy} size="large"><ErrorNotice error={error}/><form onSubmit={save}><fieldset disabled={busy} className="sk-access-form">{editor.type==='users'?<>{!editor.id&&<>{['username','email','password'].map(k=><label key={k}>{t(k)}<input autoComplete={k==='password'?'new-password':'off'} type={k==='password'?'password':k==='email'?'email':'text'} required value={draft[k]} onChange={e=>update(k,e.target.value)}/></label>)}</>}{roleSelect('role')}<label><input type="checkbox" checked={draft.administrator} onChange={e=>update('administrator',e.target.checked)}/>{t('admin')}</label>{editor.id&&<label><input type="checkbox" checked={draft.active} onChange={e=>update('active',e.target.checked)}/>{t('active')}</label>}</>:<><label>{t('name')}<input required maxLength={120} value={draft.name} onChange={e=>update('name',e.target.value)}/></label>{editor.type==='roles'?<div className="sk-access-permissions">{['crm','outreach','mail','reports','templates','automation'].map(m=><div key={m}><strong>{t(m)}</strong>{['read','write'].map(a=>{const p=m+'.'+a;return <label key={a}><input type="checkbox" checked={draft.permissions.includes(p)} onChange={e=>{let values=new Set(draft.permissions);if(e.target.checked){values.add(p);if(a==='write')values.add(m+'.read');}else{values.delete(p);if(a==='read')values.delete(m+'.write');}update('permissions',[...values]);}}/>{t(a)}</label>;})}</div>)}</div>:<>{roleSelect('teamRole')}<p>{t('members')}</p>{data.users.map(u=><label key={u.id}><input type="checkbox" checked={draft.members.includes(u.id)} onChange={e=>update('members',e.target.checked?[...draft.members,u.id]:draft.members.filter(x=>x!==u.id))}/>{u.username}</label>)}</>}</>}<div><Button type="submit" variant="primary">{t('save')}</Button><Button onClick={dismiss}>{t('cancel')}</Button></div></fieldset></form></Modal>}</div>;
}
