import {useEffect,useRef,useState} from 'react';
import {api} from '../api';
import {Button,Panel,PageFrame,Badge,ErrorNotice,Empty,dateTime} from '../redesign/ui';
import Modal from '../redesign/Modal';
import {useConfirm} from '../context/ConfirmContext';
import {useUiLanguage} from '../context/LanguageContext';
import {useAutomationText} from './automation-text';
import './automation.css';
const ROOT='/crm/automations';
const clean={name:'',trigger:'reply',mode:'approval',conditions:{},action:{type:'task',title:'',delay_days:1},daily_limit:100};
export function ContactAutomationTags({id}){const t=useAutomationText(),[tags,setTags]=useState([]);useEffect(()=>{let live=true;api.get(ROOT+'/contacts/'+id+'/tags').then(r=>{if(live)setTags(r);}).catch(()=>{});return()=>{live=false;};},[id]);return tags.length?<Panel title={t('contactTags')}><div className="sk-auto-tags">{tags.map(tag=><Badge key={tag}>{tag}</Badge>)}</div></Panel>:null;}
export default function Automations(){
 const t=useAutomationText(),{language}=useUiLanguage(),confirm=useConfirm(),lock=useRef(false),baseline=useRef('');
 const [rules,setRules]=useState([]),[runs,setRuns]=useState([]),[pipelines,setPipelines]=useState([]),[campaigns,setCampaigns]=useState([]),[filter,setFilter]=useState({rule:'',state:''}),[reload,setReload]=useState(0),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(null),[notice,setNotice]=useState(''),[editor,setEditor]=useState(null),[draft,setDraft]=useState(clean),[detail,setDetail]=useState(null);
 useEffect(()=>{let live=true;setLoading(true);setError(null);Promise.all([api.get(ROOT+'/rules'),api.get(ROOT+'/runs?'+new URLSearchParams({...(filter.rule?{rule_id:filter.rule}:{}),...(filter.state?{state:filter.state}:{})})),api.get('/crm/sales/pipelines'),api.get('/campaigns')]).then(([r,x,p,c])=>{if(live){setRules(r);setRuns(x);setPipelines(p);setCampaigns(c);}}).catch(e=>{if(live)setError(e);}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[reload,filter]);
 const mutate=async fn=>{if(lock.current)return;lock.current=true;setBusy(true);setError(null);try{await fn();setReload(n=>n+1);}catch(e){setError(e);}finally{setBusy(false);lock.current=false;}};
 const edit=row=>{setError(null);setEditor(row||{});const next=row?{name:row.name,trigger:row.trigger,mode:row.mode,conditions:{...row.conditions},action:{...row.action},daily_limit:row.daily_limit,revision:row.revision}:structuredClone(clean);setDraft(next);baseline.current=JSON.stringify(next);};
 const save=e=>{e.preventDefault();mutate(async()=>{await (editor.id?api.put(ROOT+'/rules/'+editor.id,draft):api.post(ROOT+'/rules',draft));setEditor(null);});};
 const show=async(row,kind)=>{setError(null);try{setDetail({kind,row,value:await api.get(ROOT+'/rules/'+row.id+'/'+kind)});}catch(e){setError(e);}};
 const condition=(key,value)=>setDraft(d=>{const conditions={...d.conditions};if(value)conditions[key]=['pipeline_id','campaign_id'].includes(key)?Number(value):value;else delete conditions[key];return {...d,conditions};});
 const changeAction=type=>setDraft(d=>({...d,action:type==='task'?{type,title:'',delay_days:1}:type==='tag'?{type,tag:''}:{type,stage:''}}));
 const resultText=r=>Object.entries(r||{}).filter(([k,v])=>v!==null&&typeof v!=='object').map(([k,v])=>`${t(k)}: ${['reason','type','mode','trigger'].includes(k)||typeof v==='boolean'?t(String(v)):String(v)}`).join(' · ');
 const describe=value=><dl className="sk-auto-description">{Object.entries(value||{}).filter(([,v])=>v!==null).map(([k,v])=><div key={k}><dt>{t(k)}</dt><dd>{typeof v==='object'?describe(v):['reason','type','mode','trigger','state'].includes(k)||typeof v==='boolean'?t(String(v)):String(v)}</dd></div>)}</dl>;
 const dismiss=async()=>{if(!busy&&(JSON.stringify(draft)===baseline.current||await confirm({message:t('discard'),danger:false})))setEditor(null);};
 return <PageFrame title={t('automation')} description={t('help')} actions={<><Button variant="primary" icon="plus" onClick={()=>edit(null)}>{t('new')}</Button><Button disabled={busy} onClick={()=>mutate(async()=>{const r=await api.post(ROOT+'/scan',{});setNotice(t('scanResult')+': '+r.created+' / '+r.executed);})}>{t('scan')}</Button></>}>
 <ErrorNotice error={!editor&&error}/>{notice&&<p role="status">{notice}</p>}
 <Panel title={t('rules')}>{loading?<p>{t('loading')}</p>:<div className="sk-table-wrap"><table className="sk-table"><thead><tr>{['name','trigger','action','mode','status','details'].map(k=><th key={k}>{t(k)}</th>)}</tr></thead><tbody>{rules.map(r=><tr key={r.id}><td>{r.name}</td><td>{t(r.trigger)}</td><td>{t(r.action.type)}</td><td>{t(r.mode)}</td><td><Badge tone={r.enabled?'green':'neutral'}>{t(r.enabled?'enabled':'disabled')}</Badge></td><td><div className="sk-auto-actions"><Button disabled={busy||r.enabled} title={r.enabled?t('pausedEdit'):undefined} onClick={()=>edit(r)}>{t('edit')}</Button><Button onClick={()=>show(r,'preview')}>{t('preview')}</Button><Button onClick={()=>show(r,'audit')}>{t('history')}</Button><Button disabled={busy} onClick={async()=>{if(!r.enabled&&!await confirm({message:t('enableWarning'),danger:false}))return;mutate(()=>api.post(ROOT+'/rules/'+r.id+'/enabled',{revision:r.revision,enabled:!r.enabled}));}}>{t(r.enabled?'pause':'enable')}</Button></div></td></tr>)}</tbody></table>{!rules.length&&<Empty>{t('empty')}</Empty>}</div>}</Panel>
 <Panel title={t('runs')}><div className="sk-auto-actions"><label>{t('rules')}<select value={filter.rule} onChange={e=>setFilter(f=>({...f,rule:e.target.value}))}><option value="">{t('all')}</option>{rules.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label>{t('status')}<select value={filter.state} onChange={e=>setFilter(f=>({...f,state:e.target.value}))}><option value="">{t('all')}</option>{['pending','succeeded','skipped','failed','rejected'].map(s=><option key={s} value={s}>{t(s)}</option>)}</select></label></div><div className="sk-table-wrap"><table className="sk-table"><thead><tr>{['name','event','status','date','result','action'].map(k=><th key={k}>{t(k)}</th>)}</tr></thead><tbody>{runs.map(r=><tr key={r.id}><td>{r.definition.name}</td><td>{t(r.definition.trigger)} #{r.event_id}</td><td>{t(r.state)}</td><td>{dateTime(r.created_at,{},language)}</td><td>{resultText(r.result)}</td><td><div className="sk-auto-actions"><Button onClick={()=>setDetail({kind:'run',value:r})}>{t('details')}</Button>{['pending','failed'].includes(r.state)&&['reject',r.state==='failed'?'retry':'approve'].map(action=><Button key={action} disabled={busy} onClick={async()=>{if(action!=='reject'&&!await confirm({message:t('decisionWarning'),danger:false}))return;mutate(()=>api.post(ROOT+'/runs/'+r.id+'/decision',{action,revision:rules.find(x=>x.id===r.rule_id)?.revision}));}}>{t(action)}</Button>)}</div></td></tr>)}</tbody></table>{!runs.length&&<Empty>{t('empty')}</Empty>}</div></Panel>
 {editor&&<Modal title={t(editor.id?'edit':'new')} busy={busy} onClose={dismiss}><ErrorNotice error={error}/><form onSubmit={save}><fieldset disabled={busy} className="sk-form"><label>{t('name')}<input required maxLength={120} value={draft.name} onChange={e=>setDraft(d=>({...d,name:e.target.value}))}/></label><label>{t('trigger')}<select value={draft.trigger} onChange={e=>setDraft(d=>({...d,trigger:e.target.value,conditions:{},action:{type:'task',title:'',delay_days:1}}))}>{['reply','enrollment_completed','opportunity_changed','activity_overdue','meeting_created'].map(k=><option key={k} value={k}>{t(k)}</option>)}</select></label><label>{t('mode')}<select value={draft.mode} onChange={e=>setDraft(d=>({...d,mode:e.target.value}))}>{['approval','automatic'].map(k=><option key={k} value={k}>{t(k)}</option>)}</select></label><label>{t('limit')}<input type="number" min="1" max="1000" required value={draft.daily_limit} onChange={e=>setDraft(d=>({...d,daily_limit:Number(e.target.value)}))}/></label>
 {['reply','enrollment_completed'].includes(draft.trigger)&&<label>{t('campaign')}<select value={draft.conditions.campaign_id||''} onChange={e=>condition('campaign_id',e.target.value)}><option value="">{t('all')}</option>{campaigns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}
 {draft.trigger==='opportunity_changed'&&<><label>{t('pipeline')}<select value={draft.conditions.pipeline_id||''} onChange={e=>setDraft(d=>({...d,conditions:e.target.value?{pipeline_id:Number(e.target.value)}:{},action:d.action.type==='move_stage'?{type:'move_stage',stage:''}:d.action}))}><option value="">{t('all')}</option>{pipelines.filter(p=>!p.archived_at).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>{t('conditionStage')}<select value={draft.conditions.stage||''} onChange={e=>condition('stage',e.target.value)}><option value="">{t('all')}</option>{(pipelines.find(p=>p.id===draft.conditions.pipeline_id)?.stages||[]).map(s=><option key={s.key} value={s.key}>{s.name}</option>)}</select></label><label>{t('conditionOutcome')}<select value={draft.conditions.outcome||''} onChange={e=>condition('outcome',e.target.value)}><option value="">{t('all')}</option>{['open','won','lost'].map(k=><option key={k} value={k}>{t(k)}</option>)}</select></label></>}
 <label>{t('action')}<select value={draft.action.type} onChange={e=>changeAction(e.target.value)}>{['task','tag',...(draft.trigger==='opportunity_changed'&&draft.conditions.pipeline_id?['move_stage']:[])].map(k=><option key={k} value={k}>{t(k)}</option>)}</select></label>
 {draft.action.type==='task'?<><label>{t('title')}<input required maxLength={255} value={draft.action.title} onChange={e=>setDraft(d=>({...d,action:{...d.action,title:e.target.value}}))}/></label><label>{t('delay')}<input type="number" min="0" max="365" required value={draft.action.delay_days} onChange={e=>setDraft(d=>({...d,action:{...d.action,delay_days:Number(e.target.value)}}))}/></label></>:draft.action.type==='tag'?<label>{t('tagName')}<input required maxLength={64} value={draft.action.tag} onChange={e=>setDraft(d=>({...d,action:{...d.action,tag:e.target.value}}))}/></label>:<label>{t('stage')}<select required value={draft.action.stage} onChange={e=>setDraft(d=>({...d,action:{...d.action,stage:e.target.value}}))}><option value="">—</option>{(pipelines.find(p=>p.id===draft.conditions.pipeline_id)?.stages||[]).map(s=><option key={s.key} value={s.key}>{s.name}</option>)}</select></label>}
 </fieldset><div className="sk-form-actions"><Button onClick={dismiss} disabled={busy}>{t('cancel')}</Button><Button type="submit" variant="primary" disabled={busy}>{t('save')}</Button></div></form></Modal>}
 {detail&&<Modal title={t(detail.kind==='preview'?'preview':detail.kind==='run'?'runDetails':'history')} onClose={()=>setDetail(null)}>{detail.kind==='preview'?<><p>{t('sample')}</p><p>{t(detail.value.definition.action.type)} · {resultText(detail.value.definition.action)}</p>{detail.value.items.map(x=><Panel key={x.event_id} title={t('event')+' #'+x.event_id}><p>{t(x.plan.eligible?'eligible':'notEligible')}</p><p>{resultText(x.plan)}</p><p>{resultText(x.payload)}</p></Panel>)}{!detail.value.items.length&&<Empty>{t('empty')}</Empty>}</>:detail.kind==='audit'?detail.value.map(a=><Panel key={a.id} title={a.actor_name+' · '+dateTime(a.at,{},language)}><p>{t(a.action)}</p>{describe(a.detail)}</Panel>):<><p>{t(detail.value.definition.action.type)} · {t(detail.value.state)}</p>{describe({definition:detail.value.definition,payload:detail.value.payload,result:detail.value.result,attempts:detail.value.attempts})}</>}</Modal>}
 </PageFrame>;
}
