import {useEffect,useRef,useState} from 'react';
import {Link,useNavigate,useParams} from 'react-router-dom';
import {api} from '../api';
import {Button,Panel,PageFrame,ErrorNotice,dateTime} from '../redesign/ui';
import Modal from '../redesign/Modal';
import {useConfirm} from '../context/ConfirmContext';
import {useUiLanguage} from '../context/LanguageContext';
import {useCrmText} from './crm-text';
import './crm.css';
export default function Companies(){
 const {t:ui,language}=useUiLanguage();
 const t=useCrmText(),{id}=useParams(),navigate=useNavigate(),confirm=useConfirm(),lock=useRef(false),generation=useRef(0);
 const [items,setItems]=useState([]),[data,setData]=useState(null),[query,setQuery]=useState(''),[archived,setArchived]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(null),[busy,setBusy]=useState(false),[create,setCreate]=useState(false),[form,setForm]=useState({name:'',domain:'',description:''}),[reload,setReload]=useState(0);
 useEffect(()=>{const seq=++generation.current;setLoading(true);setError(null);setData(null);const timer=setTimeout(()=>api.get(id?`/crm/companies/${id}`:`/crm/companies?q=${encodeURIComponent(query)}&archived=${archived}`).then(result=>{if(seq!==generation.current)return;if(id){setData(result);setForm({name:result.name,domain:result.domain,description:result.description});}else setItems(result);}).catch(e=>{if(seq===generation.current)setError(e);}).finally(()=>{if(seq===generation.current)setLoading(false);}),id?0:200);return()=>{clearTimeout(timer);++generation.current;};},[id,query,archived,reload]);
 const dirty=data?form.name!==data.name||form.domain!==data.domain||form.description!==data.description:create&&Object.values(form).some(Boolean);
 useEffect(()=>{const unload=e=>{if(dirty||busy){e.preventDefault();e.returnValue='';}};const leave=async e=>{const a=e.target.closest?.('a[href]');if(!a||e.button!==0||e.ctrlKey||e.metaKey||e.shiftKey||e.altKey||(!dirty&&!busy))return;const url=new URL(a.href,window.location.href);if(url.origin!==window.location.origin||url.pathname===window.location.pathname)return;e.preventDefault();e.stopPropagation();if(busy)return;if(await confirm(ui('contacts.leaveWarning')))navigate(url.pathname+url.search+url.hash);};window.addEventListener('beforeunload',unload);document.addEventListener('click',leave,true);return()=>{window.removeEventListener('beforeunload',unload);document.removeEventListener('click',leave,true);};},[dirty,busy,confirm,navigate,ui]);
 const mutate=async fn=>{if(lock.current)return;lock.current=true;setBusy(true);setError(null);try{const result=await fn();setCreate(false);if(!id&&result?.id)navigate('/companies/'+result.id);else setReload(x=>x+1);}catch(e){setError(e);}finally{lock.current=false;setBusy(false);}};
 const historyText=h=>{try{const parsed=JSON.parse(h.summary);return ['name','domain','description'].filter(k=>parsed.before[k]!==parsed.after[k]).map(k=>t(k)+': '+(parsed.before[k]||'—')+' → '+(parsed.after[k]||'—')).join(' · ');}catch{return h.summary;}};
 const fields=<fieldset disabled={busy} className="sk-crm-fields"><label>{t('name')}<input required maxLength={255} value={form.name} onChange={e=>setForm(x=>({...x,name:e.target.value}))}/></label><label>{t('domain')}<input maxLength={255} value={form.domain} onChange={e=>setForm(x=>({...x,domain:e.target.value}))}/></label><label>{t('description')}<textarea maxLength={10000} rows={4} value={form.description} onChange={e=>setForm(x=>({...x,description:e.target.value}))}/></label><Button type="submit" variant="primary" disabled={busy||!form.name.trim()}>{t('save')}</Button></fieldset>;
 return <PageFrame title={id?data?.name||t('companies'):t('companies')} description={t('companyHelp')} actions={id?<Button to="/companies">{t('back')}</Button>:<Button onClick={()=>{setForm({name:'',domain:'',description:''});setCreate(true);}}>{t('newCompany')}</Button>}><div className="sk-crm-stack"><ErrorNotice error={error}/>{loading&&id?<p role="status">{t('loading')}</p>:id?data&&<>
 <Panel title={t('description')}><form onSubmit={e=>{e.preventDefault();mutate(()=>api.patch(`/crm/companies/${id}`,form));}}>{fields}</form><Button disabled={busy||dirty} onClick={async()=>{if(await confirm(t('archiveWarning')))mutate(()=>api.post(`/crm/companies/${id}/archive`,{archived:!data.archived_at}));}}>{t(data.archived_at?'restore':'archive')}</Button></Panel>
 <Panel title={t('contacts')}><ul className="sk-crm-list">{data.contacts.map(c=><li key={c.id}><div><Link to={'/leads/'+c.id}>{c.name||c.email} · #{c.id}</Link><small>{c.email} · {c.role} {c.archived_at?'· '+t('archived'):''}</small></div></li>)}</ul>{!data.contacts.length&&<p>{t('none')}</p>}<Button to="/leads">{t('contactId')}</Button></Panel>
 <Panel title={t('history')}><ul className="sk-crm-list">{data.history.map((h,i)=><li key={i}><div><strong>{t(({create:'add',update:'save',archive:'archive',restore:'restore',contact_link:'link',contact_unlink:'remove'})[h.action]||'operation')}</strong><p>{historyText(h)}</p><small>{h.actor_name} · {dateTime(h.at,{year:'numeric'},language)}</small></div></li>)}</ul></Panel></>:<Panel title={t('companies')}><div className="sk-crm-form"><label>{t('search')}<input type="search" value={query} onChange={e=>setQuery(e.target.value)}/></label><label>{t('archived')}<select value={String(archived)} onChange={e=>setArchived(e.target.value==='true')}><option value="false">{t('active')}</option><option value="true">{t('archived')}</option></select></label></div>{loading&&<p role="status">{t('loading')}</p>}<p>{t('limited')}</p><ul className="sk-crm-list">{items.map(c=><li key={c.id}><Link to={'/companies/'+c.id}>{c.name} · #{c.id}</Link><span>{c.domain}</span></li>)}</ul>{!items.length&&<p>{t('empty')}</p>}</Panel>}</div>
 {create&&<Modal busy={busy} title={t('newCompany')} onClose={async()=>{if(!busy&&(!dirty||await confirm(ui('contacts.discardWarning'))))setCreate(false);}}><ErrorNotice error={error}/><form onSubmit={e=>{e.preventDefault();mutate(()=>api.post('/crm/companies',form));}}>{fields}</form></Modal>}
 </PageFrame>;
}
