import {useEffect,useRef,useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {api} from '../api';
import {Button,Panel,ErrorNotice,Badge,dateTime} from '../redesign/ui';
import {useConfirm} from '../context/ConfirmContext';
import {useUiLanguage} from '../context/LanguageContext';
import {useCrmText} from './crm-text';
import './crm.css';
const value=x=>typeof x==='object'?JSON.stringify(x):String(x??'—');
export default function CrmContact({id,onChanged,onDirtyChange}){
 const {t:ui,language}=useUiLanguage(),navigate=useNavigate();
 const t=useCrmText(),confirm=useConfirm(),lock=useRef(false),sequence=useRef(0);
 const [data,setData]=useState(null),[error,setError]=useState(null),[busy,setBusy]=useState(false),[companies,setCompanies]=useState([]);
 const [email,setEmail]=useState(''),[label,setLabel]=useState(''),[note,setNote]=useState(''),[company,setCompany]=useState(''),[role,setRole]=useState('');
 const [query,setQuery]=useState(''),[results,setResults]=useState([]),[source,setSource]=useState(''),[preview,setPreview]=useState(null),[choices,setChoices]=useState({});
 useEffect(()=>{let live=true;setData(null);setError(null);setPreview(null);setSource('');setQuery('');setEmail('');setLabel('');setNote('');setCompany('');setRole('');
 Promise.all([api.get(`/crm/contacts/${id}`),api.get('/crm/companies')]).then(([d,c])=>{if(live){setData(d);setCompanies(c);}}).catch(e=>{if(live)setError(e);});return()=>{live=false;sequence.current++;};},[id]);
 useEffect(()=>{let live=true;setResults([]);if(query.trim().length<2)return;const timer=setTimeout(()=>api.get('/leads?q='+encodeURIComponent(query.trim())).then(r=>{if(live)setResults(r.filter(x=>String(x.id)!==String(id)));}).catch(e=>{if(live)setError(e);}),250);return()=>{live=false;clearTimeout(timer);};},[query,id]);
 const dirty=!!(email||label||note||company||role);
 useEffect(()=>{onDirtyChange?.(dirty||busy);return()=>onDirtyChange?.(false);},[dirty,busy,onDirtyChange]);
 useEffect(()=>{const unload=e=>{if(dirty||busy){e.preventDefault();e.returnValue='';}};const leave=async e=>{const a=e.target.closest?.('a[href]');if(!a||e.button!==0||e.ctrlKey||e.metaKey||e.shiftKey||e.altKey||(!dirty&&!busy))return;const url=new URL(a.href,window.location.href);if(url.origin!==window.location.origin||url.pathname===window.location.pathname)return;e.preventDefault();e.stopPropagation();if(busy)return;if(await confirm(ui('contacts.leaveWarning')))navigate(url.pathname+url.search+url.hash);};window.addEventListener('beforeunload',unload);document.addEventListener('click',leave,true);return()=>{window.removeEventListener('beforeunload',unload);document.removeEventListener('click',leave,true);};},[dirty,busy,confirm,navigate,ui]);
 const mutate=async(fn,done)=>{if(lock.current)return;lock.current=true;setBusy(true);setError(null);const generation=sequence.current;try{await fn();const d=await api.get(`/crm/contacts/${id}`);if(generation!==sequence.current)return;setData(d);setPreview(null);done?.();onChanged?.();}catch(e){if(generation===sequence.current)setError(e);}finally{lock.current=false;setBusy(false);}};
 if(!data)return <Panel title={t('crm')}><ErrorNotice error={error}/>{!error&&<p role="status">{t('loading')}</p>}</Panel>;
 if(data.merged_into)return <Panel title={t('crm')}><p>{t('merged')} <Link to={'/leads/'+data.merged_into}>#{data.merged_into}</Link></p></Panel>;
 return <fieldset disabled={busy} className="sk-crm-stack"><ErrorNotice error={error}/>
 <Panel title={t('kind')}><label>{t('kind')}<select disabled={busy} value={data.kind} onChange={e=>mutate(()=>api.patch(`/crm/contacts/${id}/kind`,{kind:e.target.value}))}>{['unspecified','person','shared_mailbox'].map(k=><option key={k} value={k}>{t(k)}</option>)}</select></label></Panel>
 <Panel title={t('addresses')}><p>{t('addressHelp')}</p><ul className="sk-crm-list">{data.addresses.map((a,i)=><li key={a.id??'primary-'+i}><div><strong>{a.email}</strong> <span>{a.primary?t('primary'):a.label}</span> {a.suppressed&&<Badge tone="red">{t('blocked')}</Badge>}<small>{t('sourceId')}: {a.lead_id}</small></div>{!a.primary&&a.lead_id===Number(id)&&<Button disabled={busy} onClick={async()=>{if(await confirm(t('removeWarning')))mutate(()=>api.delete(`/crm/contacts/${id}/addresses/${a.id}`));}}>{t('remove')}</Button>}</li>)}</ul>
 <form className="sk-crm-form" onSubmit={e=>{e.preventDefault();mutate(()=>api.post(`/crm/contacts/${id}/addresses`,{email,label}),()=>{setEmail('');setLabel('');});}}><label>{t('address')}<input type="email" required maxLength={255} value={email} onChange={e=>setEmail(e.target.value)}/></label><label>{t('label')}<input maxLength={100} value={label} onChange={e=>setLabel(e.target.value)}/></label><Button type="submit" disabled={busy||!email.trim()}>{t('add')}</Button></form></Panel>
 <Panel title={t('companies')} action={<Button to="/companies">{t('companies')}</Button>}><ul className="sk-crm-list">{data.companies.map(c=><li key={c.relation_id}><div><Link to={'/companies/'+c.id}>{c.name}</Link><small>{c.role} · #{c.lead_id}</small></div>{c.lead_id===Number(id)&&<Button disabled={busy} onClick={async()=>{if(await confirm(t('removeWarning')))mutate(()=>api.delete(`/crm/contacts/${id}/companies/${c.id}`));}}>{t('remove')}</Button>}</li>)}</ul>
 <form className="sk-crm-form" onSubmit={e=>{e.preventDefault();mutate(()=>api.post(`/crm/contacts/${id}/companies`,{company_id:Number(company),role}),()=>{setCompany('');setRole('');});}}><label>{t('companies')}<select required value={company} onChange={e=>setCompany(e.target.value)}><option value="">{t('select')}</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name} · #{c.id}</option>)}</select></label><label>{t('role')}<input maxLength={255} value={role} onChange={e=>setRole(e.target.value)}/></label><Button type="submit" disabled={busy||!company}>{t('link')}</Button></form></Panel>
 <Panel title={t('notes')}><p>{t('noteHelp')}</p><form onSubmit={e=>{e.preventDefault();mutate(()=>api.post(`/crm/contacts/${id}/notes`,{body:note}),()=>setNote(''));}}><label>{t('note')}<textarea required maxLength={10000} rows={4} value={note} onChange={e=>setNote(e.target.value)}/></label><Button type="submit" disabled={busy||!note.trim()}>{t('add')}</Button></form><ul className="sk-crm-list">{data.notes.map(n=><li key={n.id}><div><p className="sk-crm-note">{n.body}</p><small>{n.actor_name} · {dateTime(n.created_at,{year:'numeric'},language)} · #{n.lead_id}</small></div></li>)}</ul></Panel>
 <Panel title={t('members')}><p>{t('readOnly')}</p>{data.members.length?<ul>{data.members.map(m=><li key={m.id}><Link to={'/leads/'+m.id}>{m.name||m.email} · #{m.id}</Link></li>)}</ul>:<p>{t('none')}</p>}</Panel>
 <Panel title={t('history')}>{!data.operations.length&&<p className="sk-crm-empty">{t('none')}</p>}<ul className="sk-crm-list">{data.operations.map(o=><li key={o.id}><div><strong>{ui('contacts.operation.'+o.action)}</strong><small>{o.actor_name} · {dateTime(o.at,{year:'numeric'},language)} · #{o.lead_id}</small>{o.details?.company_id&&<Link to={'/companies/'+o.details.company_id}>{o.details.name}</Link>}</div></li>)}</ul></Panel>
 <Panel title={t('merge')}><p>{t('mergeHelp')}</p><label>{t('findContact')}<input value={query} onChange={e=>{setQuery(e.target.value);setSource('');setPreview(null);}}/></label><label>{t('source')}<select value={source} disabled={busy} onChange={e=>{setSource(e.target.value);setPreview(null);}}><option value="">—</option>{results.map(r=><option key={r.id} value={r.id}>{r.name} · {r.email} · #{r.id}</option>)}</select></label><Button disabled={busy||!source} onClick={async()=>{if(lock.current)return;lock.current=true;setBusy(true);setError(null);try{setPreview(await api.get(`/crm/contacts/${id}/merge-preview?source_id=${source}`));setChoices({});}catch(e){setError(e);}finally{lock.current=false;setBusy(false);}}}>{t('preview')}</Button>
 {preview&&<div className="sk-crm-compare"><p><strong>{t('target')}:</strong> {preview.target.name} · {preview.target.email} · #{preview.target.id}</p><p><strong>{t('source')}:</strong> {preview.source.name} · {preview.source.email} · #{preview.source.id}</p><p>{t('addresses')}: {[...preview.target.addresses,...preview.source.addresses].map(a=>a.email).join(', ')}</p>{!preview.conflicts.length&&<p>{t('noConflicts')}</p>}{preview.conflicts.map(c=><fieldset key={c.field}><legend>{c.field==='name'?t('name'):c.field}</legend>{['target','source'].map(side=><label key={side}><input type="radio" name={'conflict-'+c.field} checked={choices[c.field]===side} onChange={()=>setChoices(x=>({...x,[c.field]:side}))}/>{t(side)}: {value(c[side])}</label>)}</fieldset>)}<Button variant="primary" disabled={busy||preview.conflicts.some(c=>!choices[c.field])} onClick={async()=>{if(await confirm(t('mergeWarning')))mutate(()=>api.post(`/crm/contacts/${id}/merge`,{source_id:preview.source.id,fingerprint:preview.fingerprint,choices}),()=>{setSource('');setQuery('');});}}>{t('confirmMerge')}</Button></div>}</Panel>
 </fieldset>;
}
