import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {api} from '../api';
import {Button,Panel,PageFrame,ErrorNotice,Empty} from '../redesign/ui';
import {useAutomationText} from './automation-text';
import './automation.css';
export default function CrmReports(){
 const t=useAutomationText(),[filters,setFilters]=useState({date_from:'',date_to:'',date_basis:'created',pipeline_id:'',campaign_id:'',inbox_id:'',custom_field:'',custom_value:'',inactive_days:30}),[query,setQuery]=useState(''),[report,setReport]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(null),[choices,setChoices]=useState({pipelines:[],campaigns:[],inboxes:[],fields:[]});
 useEffect(()=>{let live=true;Promise.all([api.get('/crm/sales/pipelines'),api.get('/campaigns'),api.get('/inboxes'),api.get('/contact-fields')]).then(([pipelines,campaigns,inboxes,fields])=>{if(live)setChoices({pipelines,campaigns,inboxes,fields});}).catch(e=>{if(live)setError(e);});return()=>{live=false;};},[]);
 useEffect(()=>{let live=true;setLoading(true);setError(null);api.get('/crm/reports?'+query).then(r=>{if(live)setReport(r);}).catch(e=>{if(live)setError(e);}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[query]);
 const change=(key,v)=>setFilters(f=>({...f,[key]:v,...(key==='custom_field'&&!v?{custom_value:''}:{})}));
 const apply=e=>{e.preventDefault();const q=new URLSearchParams();for(const [k,v] of Object.entries(filters))if(v!=='')q.set(k,k==='date_from'||k==='date_to'?new Date(v+'T00:00:00').toISOString():v);setQuery(q.toString());};
 const table=(title,keys,rows)=><Panel title={t(title)}><div className="sk-table-wrap"><table className="sk-table"><thead><tr>{keys.map(k=><th key={k}>{t(k)}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{keys.map(k=><td key={k}>{row[k]??'—'}</td>)}</tr>)}</tbody></table>{!rows.length&&<Empty>{t('empty')}</Empty>}</div></Panel>;
 const list=(key,rows,url)=><Panel title={t(key)}><div className="sk-auto-actions">{rows.length?rows.map(r=><Button key={r.id} to={url(r)}>{r.title||r.name||r.email}</Button>):<Empty>{t('empty')}</Empty>}</div></Panel>;
 return <PageFrame title={t('reports')} description={t('reportHelp')}><ErrorNotice error={error}/><Panel><form className="sk-auto-actions" onSubmit={apply}>{[['date_from','from'],['date_to','to']].map(([k,label])=><label key={k}>{t(label)}<input type="date" value={filters[k]} onChange={e=>change(k,e.target.value)}/></label>)}<label>{t('basis')}<select value={filters.date_basis} onChange={e=>change('date_basis',e.target.value)}>{['created','closed'].map(k=><option key={k} value={k}>{t(k)}</option>)}</select></label>{[['pipeline_id','pipeline','pipelines'],['campaign_id','campaign','campaigns'],['inbox_id','inbox','inboxes']].map(([k,label,list])=><label key={k}>{t(label)}<select value={filters[k]} onChange={e=>change(k,e.target.value)}><option value="">{t('all')}</option>{choices[list].map(x=><option key={x.id} value={x.id}>{x.name||x.email}</option>)}</select></label>)}<label>{t('customField')}<select value={filters.custom_field} onChange={e=>change('custom_field',e.target.value)}><option value="">{t('all')}</option>{choices.fields.map(f=><option key={f.key} value={f.key}>{f.label}</option>)}</select></label><label>{t('customValue')}<input disabled={!filters.custom_field} value={filters.custom_value} onChange={e=>change('custom_value',e.target.value)}/></label><label>{t('inactiveDays')}<input required type="number" min="1" max="365" value={filters.inactive_days} onChange={e=>change('inactive_days',e.target.value)}/></label><Button type="submit" variant="primary" disabled={loading}>{t('apply')}</Button></form></Panel>
 {loading?<p role="status">{t('loading')}</p>:report&&!error&&<><div className="sk-report-metrics">{['open','won','lost'].map(k=><div key={k}>{t(k)}<strong>{report.counts[k]}</strong></div>)}<div>{t('conversion')}<strong>{report.conversion.percent===null?'—':report.conversion.percent+'%'}</strong>{report.conversion.numerator} / {report.conversion.denominator}</div></div><p className="sk-report-note">{t('definitions')}</p><div className="sk-report-grid">{table('currencies',['currency','open','won','lost'],report.currencies)}{table('stages',['pipeline','stage','currency','count','value'],report.stages.map(r=>({...r,stage:r.stage_name})))}{table('sources',['campaign','inbox','currency','count','value'],report.sources.map(r=>({...r,campaign:r.campaign||t('unassigned'),inbox:r.inbox||t('unassigned')})))}{table('activities',['action','status','count'],report.activities.map(r=>({action:t(r.kind),status:t(r.status),count:r.count})))}{list('overdue',report.overdue,r=>'/sales?view=agenda'+(r.lead_id?'&lead_id='+r.lead_id:''))}{list('inactive',report.inactive,r=>'/sales?view=list'+(r.lead_id?'&lead_id='+r.lead_id:''))}{list('followup',report.followup,r=>'/leads/'+r.id)}</div></>}
 </PageFrame>;
}
