import {useCan} from '../context/Permissions';
import {useEffect,useRef,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {api} from '../api';
import {Button,Panel,PageFrame,Badge,Empty,ErrorNotice,dateTime} from '../redesign/ui';
import Modal from '../redesign/Modal';
import {useUiLanguage} from '../context/LanguageContext';
import {useConfirm} from '../context/ConfirmContext';
import {useSalesText} from './sales-text';
import './sales.css';
const ROOT='/crm/sales';
const cleanDeal={title:'',description:'',pipeline_id:'',stage:'',lead_id:null,company_id:null,value:'0',currency:'PLN',probability:0,expected_close:null,outcome:'open',outcome_reason:'',archived:false};
const cleanActivity={title:'',description:'',kind:'task',lead_id:null,company_id:null,opportunity_id:null,starts_at:null,due_at:'',reminder_at:null,snoozed_until:null,location:'',priority:'normal',status:'planned'};
export function localInput(value){if(!value)return '';const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}
export function utcInput(value){return value?new Date(value).toISOString():null;}
function picked(row,template){return Object.fromEntries(Object.keys(template).map(k=>[k,k==='archived'?!!row.archived_at:row[k]??template[k]]));}
export default function Sales(){
 const canEdit=useCan('crm.write');
 const t=useSalesText(),{language}=useUiLanguage(),confirm=useConfirm(),[params,setParams]=useSearchParams();
 const view=['board','list','agenda','calendar'].includes(params.get('view'))?params.get('view'):'board';
 const setView=v=>setParams(p=>{const n=new URLSearchParams(p);n.set('view',v);return n;});
 const [pipelines,setPipelines]=useState([]),[companies,setCompanies]=useState([]),[contacts,setContacts]=useState([]),[contactQuery,setContactQuery]=useState(''),[dealChoices,setDealChoices]=useState([]),[dealQuery,setDealQuery]=useState('');
 const [filter,setFilter]=useState({q:'',pipeline:'',outcome:'open',archived:false,status:'planned',kind:''}),[offset,setOffset]=useState(0),[result,setResult]=useState({items:[],total:0}),[loading,setLoading]=useState(true),[error,setError]=useState(null),[reload,setReload]=useState(0);
 const [activityDetails,setActivityDetails]=useState(null);
 const [editor,setEditor]=useState(null),[draft,setDraft]=useState({}),[baseline,setBaseline]=useState(''),[history,setHistory]=useState([]),[busy,setBusy]=useState(false),[selected,setSelected]=useState([]),[notice,setNotice]=useState(''),[month,setMonth]=useState(localInput(new Date()).slice(0,7));
 const lock=useRef(false),seq=useRef(0),editorSeq=useRef(0);const activities=['agenda','calendar'].includes(view),dirty=editor&&JSON.stringify(draft)!==baseline;
 useEffect(()=>{setOffset(0);},[view]);
 const context=new URLSearchParams();for(const k of ['lead_id','company_id','opportunity_id'])if(params.get(k))context.set(k,params.get(k));
 useEffect(()=>{let live=true;Promise.all([api.get(ROOT+'/pipelines'),api.get('/crm/companies')]).then(([p,c])=>{if(live){setPipelines(p);setCompanies(c);}}).catch(e=>{if(live)setError(e);});return()=>{live=false;};},[reload]);
 useEffect(()=>{const n=++seq.current;setLoading(true);setError(null);setSelected([]);const q=new URLSearchParams(context);q.set('offset',offset);q.set('limit',100);if(activities){if(view==='calendar'&&month){const [y,m]=month.split('-').map(Number);q.set('date_from',new Date(y,m-1,1).toISOString());q.set('date_to',new Date(y,m,1).toISOString());}if(filter.status)q.set('status',filter.status);if(filter.kind)q.set('kind',filter.kind);}else{q.delete('opportunity_id');q.set('q',filter.q);q.set('archived',filter.archived);if(filter.pipeline)q.set('pipeline_id',filter.pipeline);if(filter.outcome)q.set('outcome',filter.outcome);}const timer=setTimeout(()=>api.get(ROOT+(activities?'/activities?':'/opportunities?')+q).then(r=>{if(n===seq.current)setResult(r);}).catch(e=>{if(n===seq.current)setError(e);}).finally(()=>{if(n===seq.current)setLoading(false);}),180);return()=>{clearTimeout(timer);++seq.current;};},[activities,view,month,filter,offset,reload,params.toString()]);
 useEffect(()=>{if(!editor)return;let live=true;const timer=setTimeout(()=>api.get('/leads?q='+encodeURIComponent(contactQuery)).then(r=>{if(live)setContacts(r);}).catch(e=>{if(live)setError(e);}),200);return()=>{live=false;clearTimeout(timer);};},[contactQuery,!!editor]);
 useEffect(()=>{if(editor?.type!=='activity')return;let live=true;const timer=setTimeout(()=>api.get(ROOT+'/opportunities?q='+encodeURIComponent(dealQuery)).then(r=>{if(live)setDealChoices(r.items);}).catch(e=>{if(live)setError(e);}),200);return()=>{live=false;clearTimeout(timer);};},[editor?.type,dealQuery]);
 useEffect(()=>{if(!activities||editor||busy)return;const timer=setInterval(()=>{if(document.visibilityState==='visible')setReload(n=>n+1);},60000);return()=>clearInterval(timer);},[activities,editor,busy]);
 useEffect(()=>{const fn=e=>{if(dirty||busy){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',fn);return()=>window.removeEventListener('beforeunload',fn);},[dirty,busy]);
 const change=(k,v)=>setDraft(d=>({...d,[k]:v}));
 const filtering=(k,v)=>{setFilter(f=>({...f,[k]:v}));setOffset(0);};
 const openEditor=async(type,row=null,defaults={})=>{if(!canEdit&&!row)return;const request=++editorSeq.current;const template=type==='opportunity'?cleanDeal:type==='activity'?cleanActivity:{name:'',stages:[],archived:false};let d=row?{...picked(row,template),revision:row.revision}:{...template,...defaults};if(type==='opportunity'&&!row){const p=pipelines.find(p=>!p.archived_at);d={...d,pipeline_id:p?.id||'',stage:p?.stages[0]?.key||''};}if(type==='pipeline')d={...d,stages:(row?.stages||[]).map(s=>({...s}))};for(const k of ['lead_id','company_id','opportunity_id'])if(k in template&&!row&&params.get(k))d[k]=Number(params.get(k));setEditor({type,id:row?.id,originalStages:row?.stages||[]});setDraft(d);setBaseline(JSON.stringify(d));setHistory([]);setContactQuery('');setDealQuery('');setError(null);if(row)try{const h=await api.get(ROOT+'/history/'+type+'/'+row.id);if(request===editorSeq.current)setHistory(h);}catch(e){if(request===editorSeq.current)setError(e);}};
 const dismiss=async()=>{if(!busy&&(!dirty||await confirm({message:t('discard'),danger:false}))){++editorSeq.current;setEditor(null);}};
 const save=async e=>{e.preventDefault();if(!canEdit)return;if(lock.current)return;lock.current=true;setBusy(true);setError(null);try{let body={...draft};if(editor.type==='opportunity'){body.pipeline_id=Number(body.pipeline_id);body.probability=Number(body.probability);}const path=ROOT+'/'+({opportunity:'opportunities',activity:'activities',pipeline:'pipelines'})[editor.type];if(editor.id)await api.put(path+'/'+editor.id,body);else await api.post(path,body);setEditor(null);setReload(n=>n+1);}catch(e){setError(e);}finally{lock.current=false;setBusy(false);}};
 const bulkDone=async()=>{if(!canEdit)return;if(lock.current)return;lock.current=true;setBusy(true);setError(null);let completed=0;try{for(const row of result.items.filter(x=>selected.includes(x.id))){await api.put(ROOT+'/activities/'+row.id,{...picked(row,cleanActivity),revision:row.revision,status:'done'});completed++;}setSelected([]);}catch(e){setError(e);}finally{setNotice(t('bulkProgress')+': '+completed+'/'+selected.length);setReload(n=>n+1);setBusy(false);lock.current=false;}};
 const money=x=>new Intl.NumberFormat(language,{style:'currency',currency:x.currency}).format(Number(x.value));
 const field=(key,type='text',required=false)=><label>{t(key)}<input type={type} required={required} value={draft[key]??''} onChange={e=>change(key,e.target.value||null)} maxLength={type==='text'?255:undefined}/></label>;
 const options=(key,values)=><label>{t(key)}<select value={draft[key]??''} onChange={e=>key==='kind'?setDraft(d=>({...d,kind:e.target.value,starts_at:e.target.value==='task'?null:d.starts_at})):change(key,e.target.value)}>{values.map(v=><option key={v} value={v}>{t(v)}</option>)}</select></label>;
 const timeField=key=><label>{t(key==='starts_at'?'starts':key==='due_at'?'due':key==='reminder_at'?'reminder':'snooze')}<input type="datetime-local" required={key==='due_at'||(key==='starts_at'&&draft.kind==='meeting')} value={localInput(draft[key])} onChange={e=>change(key,utcInput(e.target.value))}/></label>;
 const relations=<><label>{t('contactSearch')}<input value={contactQuery} onChange={e=>setContactQuery(e.target.value)}/></label><label>{t('contact')}<select value={draft.lead_id||''} onChange={e=>change('lead_id',e.target.value?Number(e.target.value):null)}><option value="">{t('none')}</option>{draft.lead_id&&!contacts.some(c=>c.id===draft.lead_id)&&<option value={draft.lead_id}>#{draft.lead_id}</option>}{contacts.map(c=><option key={c.id} value={c.id}>{c.name||c.email} · #{c.id}</option>)}</select></label><label>{t('company')}<select value={draft.company_id||''} onChange={e=>change('company_id',e.target.value?Number(e.target.value):null)}><option value="">{t('none')}</option>{draft.company_id&&!companies.some(c=>c.id===draft.company_id)&&<option value={draft.company_id}>#{draft.company_id}</option>}{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></>;
 const links=row=><span className="sk-sales-links">{row.lead_id&&<Link to={'/leads/'+row.lead_id}>{t('contact')} #{row.lead_id}</Link>}{row.company_id&&<Link to={'/companies/'+row.company_id}>{t('company')} #{row.company_id}</Link>}{row.opportunity_id&&<span>{t('opportunity')} #{row.opportunity_id}</span>}</span>;
 const activityRow=row=><li key={row.id}><input aria-label={t('select')+' '+row.title} type="checkbox" disabled={!canEdit} checked={selected.includes(row.id)} onChange={e=>setSelected(xs=>e.target.checked?[...xs,row.id]:xs.filter(x=>x!==row.id))}/><div><button className="sk-sales-record" onClick={()=>openEditor('activity',row)}>{row.title}</button>{links(row)}<small>{t(row.kind)} · {dateTime(row.starts_at||row.due_at,{},language)}{row.starts_at&&' — '+dateTime(row.due_at,{},language)}</small></div><Badge tone={row.overdue?'red':row.reminder_due?'amber':'neutral'}>{row.overdue?t('overdue'):row.reminder_due?t('reminderDue'):t(row.status)}</Badge><Button icon="plus" aria-label={t('followup')+' '+row.title} onClick={()=>openEditor('activity',null,{lead_id:row.lead_id,company_id:row.company_id,opportunity_id:row.opportunity_id})}>{t('followup')}</Button></li>;
 const visiblePipelines=filter.pipeline?pipelines.filter(p=>String(p.id)===filter.pipeline):pipelines;
 return <PageFrame title={t(activities?view:'sales')} description={t('help')} className="sk-sales" actions={canEdit&&<><Button icon="plus" variant="primary" disabled={!pipelines.some(p=>!p.archived_at)} onClick={()=>openEditor('opportunity')}>{t('newDeal')}</Button><Button icon="calendar" onClick={()=>openEditor('activity')}>{t('newActivity')}</Button><Button icon="settings" onClick={()=>openEditor('pipeline')}>{t('newPipeline')}</Button></>}>
 {!activities&&<div className="sk-sales-tabs" role="tablist">{['board','list'].map(v=><button role="tab" aria-selected={view===v} key={v} onClick={()=>{setView(v);setOffset(0);}}>{t(v)}</button>)}</div>}
 <ErrorNotice error={!editor&&error}/>{context.size>0&&<p>{t('context')}: {['lead_id','company_id','opportunity_id'].filter(k=>params.get(k)).map(k=>t({lead_id:'contact',company_id:'company',opportunity_id:'opportunity'}[k])+' #'+params.get(k)).join(' · ')} — <Link to={'/sales?view='+view}>{t('clearContext')}</Link></p>}{notice&&<p role="status">{notice}</p>}
 <Panel className="sk-sales-filter"><div className="sk-sales-toolbar">{activities?<><label>{t('status')}<select value={filter.status} onChange={e=>filtering('status',e.target.value)}><option value="">{t('all')}</option>{['planned','done','cancelled'].map(s=><option key={s} value={s}>{t(s)}</option>)}</select></label><label>{t('kind')}<select value={filter.kind} onChange={e=>filtering('kind',e.target.value)}><option value="">{t('all')}</option>{['task','meeting'].map(s=><option key={s} value={s}>{t(s)}</option>)}</select></label></>:<><label>{t('search')}<input type="search" value={filter.q} onChange={e=>filtering('q',e.target.value)}/></label><label>{t('board')}<select value={filter.pipeline} onChange={e=>filtering('pipeline',e.target.value)}><option value="">{t('all')}</option>{pipelines.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>{t('outcome')}<select value={filter.outcome} onChange={e=>filtering('outcome',e.target.value)}><option value="">{t('all')}</option>{['open','won','lost'].map(s=><option key={s} value={s}>{t(s)}</option>)}</select></label><label>{t('archive')}<select value={String(filter.archived)} onChange={e=>filtering('archived',e.target.value==='true')}><option value="false">{t('active')}</option><option value="true">{t('archive')}</option></select></label></>}
 <Button onClick={()=>{try{localStorage.setItem('sekaro-sales-view',JSON.stringify({view,filter}));setNotice(t('viewSaved'));}catch(e){setError(e);}}}>{t('saveView')}</Button><Button onClick={()=>{try{const s=JSON.parse(localStorage.getItem('sekaro-sales-view')||'null');if(s&&['board','list','agenda','calendar'].includes(s.view)&&s.filter){setView(s.view);setFilter({...filter,...s.filter});setOffset(0);}}catch(e){setError(e);}}}>{t('loadView')}</Button><Button icon="refresh" onClick={()=>setReload(n=>n+1)} aria-label={t('reload')}/></div></Panel>
 {loading?<p role="status">{t('loading')}</p>:<>
 {view==='board'&&<>{!pipelines.length&&<Empty>{t('pipelineHelp')}</Empty>}{visiblePipelines.map(p=><Panel key={p.id} title={p.name} icon="stack" action={<Button onClick={()=>openEditor('pipeline',p)}>{t('configure')}</Button>}><div className="sk-sales-board">{p.stages.map((stage,i)=>{const rows=result.items.filter(x=>x.pipeline_id===p.id&&x.stage===stage.key);return <section key={stage.key} className={'sk-sales-column tone-'+['blue','purple','amber','green'][i%4]}><header><h3>{stage.name}</h3><Badge>{rows.length}</Badge></header>{rows.map(row=><article key={row.id} className="sk-sales-card"><button className="sk-sales-record" onClick={()=>openEditor('opportunity',row)}>{row.title}</button>{links(row)}<strong>{money(row)}</strong><div><Badge tone={row.outcome==='won'?'green':row.outcome==='lost'?'red':'blue'}>{t(row.outcome)}</Badge><span>{row.probability}%</span></div><small>{row.expected_close||'—'}</small></article>)}{!rows.length&&<p className="sk-muted">—</p>}</section>;})}</div></Panel>)}</>}
 {view==='list'&&<Panel><div className="sk-table-wrap"><table className="sk-table"><thead><tr>{['title','stage','value','probability','expected','outcome'].map(k=><th key={k}>{t(k)}</th>)}</tr></thead><tbody>{result.items.map(row=><tr key={row.id}><td><button className="sk-sales-record" onClick={()=>openEditor('opportunity',row)}>{row.title}</button>{links(row)}</td><td>{pipelines.find(p=>p.id===row.pipeline_id)?.stages.find(s=>s.key===row.stage)?.name||row.stage}</td><td>{money(row)}</td><td>{row.probability}%</td><td>{row.expected_close||'—'}</td><td><Badge>{t(row.outcome)}</Badge></td></tr>)}</tbody></table></div>{!result.items.length&&<Empty>{t('empty')}</Empty>}</Panel>}
 {activities&&<Panel title={t(view)} icon="calendar" action={selected.length>0&&<Button disabled={busy} onClick={bulkDone}>{t('bulkDone')} ({selected.length})</Button>}><p className="sk-muted">{t('internal')} {t('timezone')}: {Intl.DateTimeFormat().resolvedOptions().timeZone}</p>{view==='agenda'?<ul className="sk-sales-agenda">{result.items.map(activityRow)}</ul>:<><label className="sk-sales-month">{t('month')}<input type="month" value={month} onChange={e=>{setMonth(e.target.value);setOffset(0);}}/></label><p className="sk-muted">{t('monthHelp')}</p><div className="sk-sales-calendar-wrap"><div className="sk-sales-calendar">{month&&Array.from({length:(new Date(month+'-01T12:00:00').getDay()+6)%7},(_,i)=><div className="sk-sales-calendar-blank" key={'blank'+i} aria-hidden="true"/>)}{month&&Array.from({length:new Date(Number(month.slice(0,4)),Number(month.slice(5,7)),0).getDate()},(_,i)=>{const day=month+'-'+String(i+1).padStart(2,'0');const start=new Date(day+'T00:00:00'),end=new Date(start);end.setDate(end.getDate()+1);const rows=result.items.filter(r=>r.starts_at?new Date(r.starts_at)<end&&new Date(r.due_at)>start:localInput(r.due_at).slice(0,10)===day);const d=new Date(day+'T12:00:00');return <section key={day}><header><strong>{i+1}</strong><small>{d.toLocaleDateString(language,{weekday:'short'})}</small></header>{rows.map(row=><button key={row.id} className={'sk-sales-calendar-item '+(row.kind==='meeting'?'is-meeting':'')} onClick={()=>setActivityDetails(row)}><time>{localInput(row.starts_at||row.due_at).slice(11)}</time> {row.title}</button>)}</section>;})}</div></div></>}{!result.items.length&&<Empty>{t('empty')}</Empty>}</Panel>}
 <div className="sk-sales-pagination"><span>{t('total')}: {result.total} · {result.total?offset+1:0}–{Math.min(offset+100,result.total)}</span><Button disabled={offset===0} onClick={()=>setOffset(n=>Math.max(0,n-100))}>{t('prev')}</Button><Button disabled={offset+100>=result.total} onClick={()=>setOffset(n=>n+100)}>{t('next')}</Button></div></>}
 {activityDetails&&<Modal title={t('activityDetails')} onClose={()=>setActivityDetails(null)} size="large">
 <div className="sk-sales-detail"><h3>{activityDetails.title}</h3><Badge>{t(activityDetails.status)}</Badge>
 <dl>{[['kind',t(activityDetails.kind)],['description',activityDetails.description],['starts',activityDetails.starts_at&&dateTime(activityDetails.starts_at,{year:'numeric'},language)],['due',dateTime(activityDetails.due_at,{year:'numeric'},language)],['location',activityDetails.location],['priority',t(activityDetails.priority)],['reminder',activityDetails.reminder_at&&dateTime(activityDetails.reminder_at,{year:'numeric'},language)],['snooze',activityDetails.snoozed_until&&dateTime(activityDetails.snoozed_until,{year:'numeric'},language)]].map(([key,value])=><div key={key}><dt>{t(key)}</dt><dd>{value||'—'}</dd></div>)}</dl>
 {links(activityDetails)}<p className="sk-muted">{t('timezone')}: {Intl.DateTimeFormat().resolvedOptions().timeZone}</p>
 <div className="sk-sales-toolbar"><Button disabled={!canEdit} variant="primary" onClick={()=>{const row=activityDetails;setActivityDetails(null);openEditor('activity',row);}}>{t('edit')}</Button><Button onClick={()=>setActivityDetails(null)}>{t('close')}</Button></div></div>
 </Modal>}
 {editor&&<Modal title={t(editor.type==='pipeline'?'configure':editor.type==='opportunity'?'opportunity':draft.kind)} busy={busy} onClose={dismiss} size="large"><ErrorNotice error={error}/><form onSubmit={save}><fieldset disabled={busy||!canEdit} className="sk-sales-form">
 {editor.type==='pipeline'?<>{field('name','text',true)}<div className="sk-sales-wide"><p>{t('stages')}</p>{draft.stages.map((stage,i)=><div className="sk-sales-toolbar" key={stage.key}><label>{t('stage')} {i+1}<input required maxLength={120} value={stage.name} onChange={e=>change('stages',draft.stages.map((s,j)=>i===j?{...s,name:e.target.value}:s))}/></label><Button aria-label={t('prev')+' '+stage.name} disabled={i===0} onClick={()=>{const a=[...draft.stages];[a[i-1],a[i]]=[a[i],a[i-1]];change('stages',a);}}>↑</Button><Button aria-label={t('next')+' '+stage.name} disabled={i===draft.stages.length-1} onClick={()=>{const a=[...draft.stages];[a[i+1],a[i]]=[a[i],a[i+1]];change('stages',a);}}>↓</Button><Button aria-label={t('removeStage')+' '+stage.name} onClick={()=>change('stages',draft.stages.filter((_,j)=>j!==i))}>×</Button></div>)}<Button disabled={draft.stages.length>=20} onClick={()=>change('stages',[...draft.stages,{key:'stage_'+Date.now(),name:''}])}>{t('addStage')}</Button><p className="sk-muted">{t('stageHelp')}</p></div></>:<>{field('title','text',true)}<label>{t('description')}<textarea rows={3} maxLength={10000} value={draft.description||''} onChange={e=>change('description',e.target.value)}/></label>{relations}
 {editor.type==='opportunity'?<><label>{t('board')}<select required value={draft.pipeline_id} onChange={e=>{const p=pipelines.find(x=>x.id===Number(e.target.value));setDraft(d=>({...d,pipeline_id:p.id,stage:p.stages[0].key}));}}>{pipelines.filter(p=>!p.archived_at||p.id===draft.pipeline_id).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>{t('stage')}<select value={draft.stage} onChange={e=>change('stage',e.target.value)}>{pipelines.find(p=>p.id===Number(draft.pipeline_id))?.stages.map(s=><option key={s.key} value={s.key}>{s.name}</option>)}</select></label><label>{t('value')}<input type="number" min="0" step="0.01" required value={draft.value} onChange={e=>change('value',e.target.value)}/></label>{field('currency','text',true)}<label>{t('probability')}<input type="number" min="0" max="100" required value={draft.probability} onChange={e=>change('probability',e.target.value)}/></label><label>{t('expected')}<input type="date" value={draft.expected_close||''} onChange={e=>change('expected_close',e.target.value||null)}/></label>{options('outcome',['open','won','lost'])}<label>{t('reason')}<textarea required={draft.outcome==='lost'} value={draft.outcome_reason} onChange={e=>change('outcome_reason',e.target.value)}/></label></>:<>{options('kind',['task','meeting'])}{draft.kind==='meeting'&&timeField('starts_at')}{timeField('due_at')}{timeField('reminder_at')}{timeField('snoozed_until')}{field('location')}{options('priority',['low','normal','high'])}{options('status',['planned','done','cancelled'])}<label>{t('search')}<input value={dealQuery} onChange={e=>setDealQuery(e.target.value)}/></label><label>{t('opportunity')}<select value={draft.opportunity_id||''} onChange={e=>{const id=e.target.value?Number(e.target.value):null;const opportunity=dealChoices.find(x=>x.id===id);setDraft(d=>({...d,opportunity_id:id,lead_id:d.lead_id||opportunity?.lead_id||null,company_id:d.company_id||opportunity?.company_id||null}));}}><option value="">{t('none')}</option>{draft.opportunity_id&&!dealChoices.some(x=>x.id===draft.opportunity_id)&&<option value={draft.opportunity_id}>#{draft.opportunity_id}</option>}{dealChoices.map(x=><option key={x.id} value={x.id}>{x.title} · #{x.id}</option>)}</select></label><p className="sk-sales-wide sk-muted">{t('internal')} {t('timezone')}: {Intl.DateTimeFormat().resolvedOptions().timeZone}</p></>}
 </>}{editor.type!=='activity'&&<label className="sk-sales-check"><input type="checkbox" checked={draft.archived} onChange={e=>change('archived',e.target.checked)}/>{t('archived')}</label>}
 <div className="sk-sales-wide sk-sales-toolbar"><Button type="submit" variant="primary" disabled={busy}>{t('save')}</Button><Button onClick={dismiss}>{t('cancel')}</Button>{editor.type==='opportunity'&&editor.id&&<Button disabled={dirty||busy} onClick={()=>openEditor('activity',null,{opportunity_id:editor.id,lead_id:draft.lead_id,company_id:draft.company_id})}>{t('newActivity')}</Button>}</div></fieldset></form>
 {history.length>0&&<details className="sk-sales-history"><summary>{t('history')} ({history.length})</summary>{history.map(h=><article key={h.id}><strong>{h.actor_name}</strong> · {dateTime(h.at,{year:'numeric'},language)}<p>{h.changes.before?t('changed'):t('created')} · {t('revision')} {h.changes.after.revision}</p><dl>{Object.entries(h.changes.after).filter(([k,v])=>!['id','revision','created_at','updated_at'].includes(k)&&JSON.stringify(v)!==JSON.stringify(h.changes.before?.[k])).map(([k,v])=><div key={k}><dt>{t(({expected_close:'expected',outcome_reason:'reason',lead_id:'contact',company_id:'company',pipeline_id:'board',opportunity_id:'opportunity',due_at:'due',starts_at:'starts',reminder_at:'reminder',snoozed_until:'snooze',archived_at:'archived',closed_at:'closed'})[k]||k)}</dt><dd>{h.changes.before&&String(h.changes.before[k]??'—')+' → '}{typeof v==='object'?JSON.stringify(v):String(v??'—')}</dd></div>)}</dl></article>)}</details>}
 </Modal>}
 </PageFrame>;
}
