import {useUiLanguage} from '../context/LanguageContext';
const words={
  "pl": {
    "name": "Nazwa pipeline",
    "addStage": "Dodaj etap",
    "removeStage": "Usuń etap",
    "stageHelp": "Etapy można nazywać i przesuwać. Nie można usunąć etapu, do którego należą szanse.",
    "sales": "Sprzedaż",
    "help": "Szanse i działania CRM. Wyniki sprzedaży nie zmieniają wysyłki.",
    "board": "Pipeline",
    "list": "Lista szans",
    "agenda": "Zadania i spotkania",
    "calendar": "Kalendarz CRM",
    "newDeal": "Dodaj szansę",
    "newActivity": "Dodaj działanie",
    "configure": "Konfiguruj pipeline",
    "newPipeline": "Nowy pipeline",
    "title": "Nazwa",
    "description": "Opis",
    "stage": "Etap",
    "value": "Wartość",
    "currency": "Waluta (ISO)",
    "probability": "Prawdopodobieństwo (%)",
    "expected": "Planowane zamknięcie",
    "outcome": "Wynik",
    "open": "Otwarta",
    "won": "Wygrana",
    "lost": "Przegrana",
    "reason": "Powód wyniku",
    "company": "Firma",
    "contact": "Kontakt",
    "contactSearch": "Szukaj kontaktu",
    "none": "Bez powiązania",
    "all": "Wszystkie",
    "save": "Zapisz",
    "cancel": "Anuluj",
    "close": "Zamknij",
    "search": "Szukaj szansy",
    "empty": "Brak rekordów dla tych filtrów.",
    "loading": "Wczytywanie…",
    "edit": "Edytuj",
    "history": "Historia zmian",
    "created": "Utworzono",
    "changed": "Zmieniono",
    "revision": "Wersja rekordu",
    "archive": "Archiwum",
    "active": "Bieżące",
    "archived": "Zarchiwizowany",
    "task": "Zadanie",
    "meeting": "Spotkanie",
    "kind": "Rodzaj",
    "starts": "Początek",
    "due": "Termin / koniec",
    "reminder": "Przypomnienie w panelu",
    "snooze": "Odłóż przypomnienie do",
    "location": "Miejsce / link spotkania",
    "priority": "Priorytet",
    "low": "Niski",
    "normal": "Normalny",
    "high": "Wysoki",
    "status": "Status",
    "planned": "Zaplanowane",
    "done": "Zakończone",
    "cancelled": "Anulowane",
    "overdue": "Po terminie",
    "reminderDue": "Przypomnienie",
    "opportunity": "Szansa",
    "timezone": "Czas lokalny przeglądarki",
    "internal": "Spotkania i przypomnienia są wewnętrzne. Nie wysyłają zaproszeń ani wiadomości.",
    "stages": "Etapy",
    "pipelineHelp": "Utwórz pierwszy pipeline, aby dodać szanse.",
    "next": "Dalej",
    "prev": "Wstecz",
    "total": "Wyniki",
    "viewSaved": "Widok zapisany w tej przeglądarce.",
    "saveView": "Zapisz widok",
    "loadView": "Wczytaj widok",
    "discard": "Odrzucić niezapisane zmiany?",
    "reload": "Odśwież dane",
    "followup": "Dodaj kolejne działanie",
    "month": "Miesiąc",
    "monthHelp": "Kalendarz pokazuje pobraną stronę działań. Użyj paginacji, aby przejrzeć pozostałe.",
    "select": "Wybierz",
    "bulkDone": "Zakończ zaznaczone",
    "context": "Powiązane rekordy",
    "clearContext": "Pokaż wszystkie",
    "bulkProgress": "Zakończone działania",
    "closed": "Data zamknięcia"
  },
  "en": {
    "name": "Pipeline name",
    "addStage": "Add stage",
    "removeStage": "Remove stage",
    "stageHelp": "Stages can be renamed and reordered. A stage containing opportunities cannot be removed.",
    "sales": "Sales",
    "help": "CRM opportunities and activities. Sales outcomes do not change sending.",
    "board": "Pipeline",
    "list": "Opportunities",
    "agenda": "Tasks and meetings",
    "calendar": "CRM calendar",
    "newDeal": "Add opportunity",
    "newActivity": "Add activity",
    "configure": "Configure pipeline",
    "newPipeline": "New pipeline",
    "title": "Title",
    "description": "Description",
    "stage": "Stage",
    "value": "Value",
    "currency": "Currency (ISO)",
    "probability": "Probability (%)",
    "expected": "Expected close",
    "outcome": "Outcome",
    "open": "Open",
    "won": "Won",
    "lost": "Lost",
    "reason": "Outcome reason",
    "company": "Company",
    "contact": "Contact",
    "contactSearch": "Search contacts",
    "none": "No link",
    "all": "All",
    "save": "Save",
    "cancel": "Cancel",
    "close": "Close",
    "search": "Search opportunities",
    "empty": "No records match these filters.",
    "loading": "Loading…",
    "edit": "Edit",
    "history": "Change history",
    "created": "Created",
    "changed": "Changed",
    "revision": "Record version",
    "archive": "Archive",
    "active": "Current",
    "archived": "Archived",
    "task": "Task",
    "meeting": "Meeting",
    "kind": "Type",
    "starts": "Start",
    "due": "Due / end",
    "reminder": "In-app reminder",
    "snooze": "Snooze reminder until",
    "location": "Location / meeting link",
    "priority": "Priority",
    "low": "Low",
    "normal": "Normal",
    "high": "High",
    "status": "Status",
    "planned": "Planned",
    "done": "Done",
    "cancelled": "Cancelled",
    "overdue": "Overdue",
    "reminderDue": "Reminder",
    "opportunity": "Opportunity",
    "timezone": "Browser local time",
    "internal": "Meetings and reminders are internal. No invitations or messages are sent.",
    "stages": "Stages",
    "pipelineHelp": "Create a pipeline to add opportunities.",
    "next": "Next",
    "prev": "Previous",
    "total": "Results",
    "viewSaved": "View saved in this browser.",
    "saveView": "Save view",
    "loadView": "Load view",
    "discard": "Discard unsaved changes?",
    "reload": "Reload data",
    "followup": "Add follow-up",
    "month": "Month",
    "monthHelp": "Calendar shows the loaded page of activities. Use pagination to review more.",
    "select": "Select",
    "bulkDone": "Complete selected",
    "context": "Linked records",
    "clearContext": "Show all",
    "bulkProgress": "Completed activities",
    "closed": "Closed at"
  },
  "de": {
    "name": "Pipeline-Name",
    "addStage": "Phase hinzufügen",
    "removeStage": "Phase entfernen",
    "stageHelp": "Phasen können umbenannt und verschoben werden. Phasen mit Verkaufschancen können nicht gelöscht werden.",
    "sales": "Vertrieb",
    "help": "CRM-Chancen und Aktivitäten. Ergebnisse ändern keinen Versand.",
    "board": "Pipeline",
    "list": "Chancenliste",
    "agenda": "Aufgaben und Termine",
    "calendar": "CRM-Kalender",
    "newDeal": "Chance hinzufügen",
    "newActivity": "Aktivität hinzufügen",
    "configure": "Pipeline konfigurieren",
    "newPipeline": "Neue Pipeline",
    "title": "Titel",
    "description": "Beschreibung",
    "stage": "Phase",
    "value": "Wert",
    "currency": "Währung (ISO)",
    "probability": "Wahrscheinlichkeit (%)",
    "expected": "Erwarteter Abschluss",
    "outcome": "Ergebnis",
    "open": "Offen",
    "won": "Gewonnen",
    "lost": "Verloren",
    "reason": "Ergebnisgrund",
    "company": "Firma",
    "contact": "Kontakt",
    "contactSearch": "Kontakt suchen",
    "none": "Keine Verknüpfung",
    "all": "Alle",
    "save": "Speichern",
    "cancel": "Abbrechen",
    "close": "Schließen",
    "search": "Chance suchen",
    "empty": "Keine passenden Datensätze.",
    "loading": "Wird geladen…",
    "edit": "Bearbeiten",
    "history": "Änderungsverlauf",
    "created": "Erstellt",
    "changed": "Geändert",
    "revision": "Datensatzversion",
    "archive": "Archiv",
    "active": "Aktuell",
    "archived": "Archiviert",
    "task": "Aufgabe",
    "meeting": "Termin",
    "kind": "Typ",
    "starts": "Beginn",
    "due": "Frist / Ende",
    "reminder": "Erinnerung im Panel",
    "snooze": "Erinnerung verschieben bis",
    "location": "Ort / Terminlink",
    "priority": "Priorität",
    "low": "Niedrig",
    "normal": "Normal",
    "high": "Hoch",
    "status": "Status",
    "planned": "Geplant",
    "done": "Erledigt",
    "cancelled": "Abgesagt",
    "overdue": "Überfällig",
    "reminderDue": "Erinnerung",
    "opportunity": "Chance",
    "timezone": "Lokale Browserzeit",
    "internal": "Termine und Erinnerungen sind intern. Keine Einladungen oder Nachrichten.",
    "stages": "Phasen",
    "pipelineHelp": "Erstellen Sie eine Pipeline für Chancen.",
    "next": "Weiter",
    "prev": "Zurück",
    "total": "Ergebnisse",
    "viewSaved": "Ansicht in diesem Browser gespeichert.",
    "saveView": "Ansicht speichern",
    "loadView": "Ansicht laden",
    "discard": "Ungespeicherte Änderungen verwerfen?",
    "reload": "Daten neu laden",
    "followup": "Folgeaktivität hinzufügen",
    "month": "Monat",
    "monthHelp": "Kalender zeigt die geladene Seite. Weitere Einträge über die Seitennavigation.",
    "select": "Auswählen",
    "bulkDone": "Auswahl abschließen",
    "context": "Verknüpfte Einträge",
    "clearContext": "Alle anzeigen",
    "bulkProgress": "Abgeschlossene Aktivitäten",
    "closed": "Abgeschlossen am"
  },
  "ru": {
    "name": "Название воронки",
    "addStage": "Добавить этап",
    "removeStage": "Удалить этап",
    "stageHelp": "Этапы можно переименовывать и перемещать. Этап со сделками нельзя удалить.",
    "sales": "Продажи",
    "help": "Сделки и действия CRM. Результаты не меняют отправку.",
    "board": "Воронка",
    "list": "Сделки",
    "agenda": "Задачи и встречи",
    "calendar": "Календарь CRM",
    "newDeal": "Добавить сделку",
    "newActivity": "Добавить действие",
    "configure": "Настроить воронку",
    "newPipeline": "Новая воронка",
    "title": "Название",
    "description": "Описание",
    "stage": "Этап",
    "value": "Сумма",
    "currency": "Валюта (ISO)",
    "probability": "Вероятность (%)",
    "expected": "Ожидаемое закрытие",
    "outcome": "Результат",
    "open": "Открыта",
    "won": "Выиграна",
    "lost": "Проиграна",
    "reason": "Причина результата",
    "company": "Компания",
    "contact": "Контакт",
    "contactSearch": "Поиск контакта",
    "none": "Без связи",
    "all": "Все",
    "save": "Сохранить",
    "cancel": "Отмена",
    "close": "Закрыть",
    "search": "Поиск сделки",
    "empty": "Нет записей по этим фильтрам.",
    "loading": "Загрузка…",
    "edit": "Изменить",
    "history": "История изменений",
    "created": "Создано",
    "changed": "Изменено",
    "revision": "Версия записи",
    "archive": "Архив",
    "active": "Текущие",
    "archived": "В архиве",
    "task": "Задача",
    "meeting": "Встреча",
    "kind": "Тип",
    "starts": "Начало",
    "due": "Срок / конец",
    "reminder": "Напоминание в панели",
    "snooze": "Отложить напоминание до",
    "location": "Место / ссылка встречи",
    "priority": "Приоритет",
    "low": "Низкий",
    "normal": "Обычный",
    "high": "Высокий",
    "status": "Статус",
    "planned": "Запланировано",
    "done": "Завершено",
    "cancelled": "Отменено",
    "overdue": "Просрочено",
    "reminderDue": "Напоминание",
    "opportunity": "Сделка",
    "timezone": "Местное время браузера",
    "internal": "Встречи и напоминания внутренние. Приглашения и сообщения не отправляются.",
    "stages": "Этапы",
    "pipelineHelp": "Создайте воронку для сделок.",
    "next": "Далее",
    "prev": "Назад",
    "total": "Результаты",
    "viewSaved": "Вид сохранён в этом браузере.",
    "saveView": "Сохранить вид",
    "loadView": "Загрузить вид",
    "discard": "Отменить несохранённые изменения?",
    "reload": "Обновить данные",
    "followup": "Добавить следующее действие",
    "month": "Месяц",
    "monthHelp": "Календарь показывает загруженную страницу. Используйте пагинацию для остальных.",
    "select": "Выбрать",
    "bulkDone": "Завершить выбранные",
    "context": "Связанные записи",
    "clearContext": "Показать все",
    "bulkProgress": "Завершённые действия",
    "closed": "Дата закрытия"
  }
};
export function useSalesText(){const {language}=useUiLanguage();return key=>(words[language]||words.pl)[key]||key;}
